# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute as @n[tag=aj.ginunga.root] at @s run function animated_java:ginunga/animations/pause_all
execute as @n[tag=aj.ginunga.root] at @s run function animated_java:ginunga/animations/animation.model.cry/play
