# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.chain_blast.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'chain_blast', 'function_path': 'animated_java:chain_blast/animations/animation.model.blast/next_frame'}
execute if score @s aj.animation.model.blast.frame matches 111.. run scoreboard players set @s aj.animation.model.blast.frame 1
data remove storage aj:temp args
execute store result storage aj:temp args.frame int 1 run scoreboard players get @s aj.animation.model.blast.frame
execute at @s run function animated_java:chain_blast/animations/animation.model.blast/zzz/apply_frame with storage aj:temp args
scoreboard players add @s aj.animation.model.blast.frame 1