# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:magic_crafting_table/root/zzz/on_tick/select_locator_locator with entity @s data.locators.locator
function animated_java:magic_crafting_table/root/zzz/on_tick/select_locator_locator3 with entity @s data.locators.locator3
function animated_java:magic_crafting_table/root/zzz/on_tick/select_locator_locator2 with entity @s data.locators.locator2
function animated_java:magic_crafting_table/root/zzz/on_tick/select_locator_locator4 with entity @s data.locators.locator4
function animated_java:magic_crafting_table/root/zzz/on_tick/select_locator_locator5 with entity @s data.locators.locator5
function animated_java:magic_crafting_table/root/zzz/on_tick/select_locator_locator6 with entity @s data.locators.locator6
function animated_java:magic_crafting_table/root/zzz/on_tick/select_locator_core with entity @s data.locators.core
function animated_java:magic_crafting_table/root/zzz/on_tick/select_locator_crafted with entity @s data.locators.crafted
function animated_java:magic_crafting_table/root/zzz/on_tick/select_locator_locator7 with entity @s data.locators.locator7
function animated_java:magic_crafting_table/root/zzz/on_tick/select_locator_locator8 with entity @s data.locators.locator8