# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tp @s ~ ~ ~ ~ ~
data merge entity @s {Invulnerable:0b}
playsound trip_magic:entity.ginunga.tp.out hostile @a ~ ~ ~ 1 1
particle dust{color:[0.02,0,0.314],scale:1} ~ ~0.5 ~ 0.25 0.5 0.25 0.01 100 force
particle dust{color:[0.239,0,0.431],scale:1} ~ ~0.5 ~ 0.25 0.5 0.25 0.01 100 force
