# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_bone5) {transformation: [-0.9298f,-1.9939f,0f,1.0132f,-1.0876f,0.5071f,0f,0.8571f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone4) {transformation: [-2.0673f,-0.7524f,0f,1.5845f,-0.4104f,1.1276f,0f,0.0008f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone3) {transformation: [-2.1979f,0.096f,0f,1.5126f,0.0523f,1.1989f,0f,-0.8984f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone2) {transformation: [-2.1979f,0.096f,0f,1.5126f,0.0523f,1.1989f,0f,-0.8984f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone1) {transformation: [-2.1979f,0.096f,0f,1.5813f,0.0523f,1.1989f,0f,-0.9f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone10) {transformation: [0f,0f,-2.2f,0f,-1.0876f,0.5071f,0f,0.8571f,1.0143f,2.1751f,0f,-1.1053f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone9) {transformation: [0f,0f,-2.2f,0f,-0.4104f,1.1276f,0f,0.0008f,2.2553f,0.8208f,0f,-1.7286f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone8) {transformation: [0f,0f,-2.2f,0f,0.0523f,1.1989f,0f,-0.8984f,2.3977f,-0.1047f,0f,-1.6501f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone7) {transformation: [0f,0f,-2.2f,0f,0.0523f,1.1989f,0f,-0.8984f,2.3977f,-0.1047f,0f,-1.6501f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone6) {transformation: [0f,0f,-2.2f,0f,0.0523f,1.1989f,0f,-0.9f,2.3977f,-0.1047f,0f,-1.725f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone20) {transformation: [0.9298f,1.9939f,0f,-1.0132f,-1.0876f,0.5071f,0f,0.8571f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone19) {transformation: [2.0673f,0.7524f,0f,-1.5845f,-0.4104f,1.1276f,0f,0.0008f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone18) {transformation: [2.1979f,-0.096f,0f,-1.5126f,0.0523f,1.1989f,0f,-0.8984f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone17) {transformation: [2.1979f,-0.096f,0f,-1.5126f,0.0523f,1.1989f,0f,-0.8984f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone16) {transformation: [2.1979f,-0.096f,0f,-1.5812f,0.0523f,1.1989f,0f,-0.9f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone15) {transformation: [0f,0f,2.2f,0f,-1.0876f,0.5071f,0f,0.8571f,-1.0143f,-2.1751f,0f,1.1053f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone14) {transformation: [0f,0f,2.2f,0f,-0.4104f,1.1276f,0f,0.0008f,-2.2553f,-0.8208f,0f,1.7286f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone13) {transformation: [0f,0f,2.2f,0f,0.0523f,1.1989f,0f,-0.8984f,-2.3977f,0.1047f,0f,1.6501f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone12) {transformation: [0f,0f,2.2f,0f,0.0523f,1.1989f,0f,-0.8984f,-2.3977f,0.1047f,0f,1.6501f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone11) {transformation: [0f,0f,2.2f,0f,0.0523f,1.1989f,0f,-0.9f,-2.3977f,0.1047f,0f,1.725f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}

playsound block.chain.break hostile @a ~1.25 ~ ~ 1 1
playsound block.chain.break hostile @a ~-1.25 ~ ~ 1 1
playsound block.chain.break hostile @a ~ ~ ~1.25 1 1
playsound block.chain.break hostile @a ~ ~ ~-1.25 1 1

execute as @n[tag=aj.chain_blast.root] at @s as @e[distance=..3] at @s run damage @s 0.25 ls_trip_and_magic:entity/ginunga/chain_blast
execute as @n[tag=aj.chain_blast.root] at @s run effect give @e[distance=..2] slowness 1 2 true