# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_bone5) {transformation: [-0.4104f,-2.1614f,0f,0.6444f,-1.1789f,0.2238f,0f,0.9757f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone4) {transformation: [-1.9195f,-1.075f,0f,1.4607f,-0.5863f,1.047f,0f,0.1806f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone3) {transformation: [-2.1983f,-0.0864f,0f,1.5255f,-0.0471f,1.1991f,0f,-0.7187f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone2) {transformation: [-2.1983f,0.0864f,0f,1.5126f,0.0471f,1.1991f,0f,-0.8985f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone1) {transformation: [-2.1983f,0.0864f,0f,1.5813f,0.0471f,1.1991f,0f,-0.9f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone10) {transformation: [0f,0f,-2.2f,0f,-1.1789f,0.2238f,0f,0.9757f,0.4477f,2.3579f,0f,-0.703f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone9) {transformation: [0f,0f,-2.2f,0f,-0.5863f,1.047f,0f,0.1806f,2.094f,1.1727f,0f,-1.5935f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone8) {transformation: [0f,0f,-2.2f,0f,-0.0471f,1.1991f,0f,-0.7187f,2.3981f,0.0942f,0f,-1.6642f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone7) {transformation: [0f,0f,-2.2f,0f,0.0471f,1.1991f,0f,-0.8985f,2.3981f,-0.0942f,0f,-1.6501f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone6) {transformation: [0f,0f,-2.2f,0f,0.0471f,1.1991f,0f,-0.9f,2.3981f,-0.0942f,0f,-1.725f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone20) {transformation: [0.4104f,2.1614f,0f,-0.6444f,-1.1789f,0.2238f,0f,0.9757f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone19) {transformation: [1.9195f,1.075f,0f,-1.4607f,-0.5863f,1.047f,0f,0.1806f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone18) {transformation: [2.1983f,0.0864f,0f,-1.5255f,-0.0471f,1.1991f,0f,-0.7187f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone17) {transformation: [2.1983f,-0.0864f,0f,-1.5126f,0.0471f,1.1991f,0f,-0.8985f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone16) {transformation: [2.1983f,-0.0864f,0f,-1.5812f,0.0471f,1.1991f,0f,-0.9f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone15) {transformation: [0f,0f,2.2f,0f,-1.1789f,0.2238f,0f,0.9757f,-0.4477f,-2.3579f,0f,0.703f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone14) {transformation: [0f,0f,2.2f,0f,-0.5863f,1.047f,0f,0.1806f,-2.094f,-1.1727f,0f,1.5935f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone13) {transformation: [0f,0f,2.2f,0f,-0.0471f,1.1991f,0f,-0.7187f,-2.3981f,-0.0942f,0f,1.6642f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone12) {transformation: [0f,0f,2.2f,0f,0.0471f,1.1991f,0f,-0.8985f,-2.3981f,0.0942f,0f,1.6501f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone11) {transformation: [0f,0f,2.2f,0f,0.0471f,1.1991f,0f,-0.9f,-2.3981f,0.0942f,0f,1.725f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}

playsound block.chain.break hostile @a ~1.25 ~ ~ 1 1
playsound block.chain.break hostile @a ~-1.25 ~ ~ 1 1
playsound block.chain.break hostile @a ~ ~ ~1.25 1 1
playsound block.chain.break hostile @a ~ ~ ~-1.25 1 1

execute as @n[tag=aj.chain_blast.root] at @s as @e[distance=..3] at @s run damage @s 0.25 ch_trip_and_magic:entity/ginunga/chain_blast
execute as @n[tag=aj.chain_blast.root] at @s run effect give @e[distance=..2] slowness 1 2 true