# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_bone5) {transformation: [0.6707f,-2.0953f,0f,-0.0299f,-1.1429f,-0.3658f,0f,1.1347f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone4) {transformation: [-1.4792f,-1.6285f,0f,1.2068f,-0.8883f,0.8068f,0f,0.522f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone3) {transformation: [-2.1539f,-0.448f,0f,1.5428f,-0.2444f,1.1749f,0f,-0.3591f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone2) {transformation: [-2.199f,0.0672f,0f,1.5125f,0.0366f,1.1994f,0f,-0.8989f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone1) {transformation: [-2.199f,0.0672f,0f,1.5813f,0.0366f,1.1994f,0f,-0.9f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone10) {transformation: [0f,0f,-2.2f,0f,-1.1429f,-0.3658f,0f,1.1347f,-0.7317f,2.2857f,0f,0.0326f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone9) {transformation: [0f,0f,-2.2f,0f,-0.8883f,0.8068f,0f,0.522f,1.6137f,1.7765f,0f,-1.3165f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone8) {transformation: [0f,0f,-2.2f,0f,-0.2444f,1.1749f,0f,-0.3591f,2.3497f,0.4887f,0f,-1.683f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone7) {transformation: [0f,0f,-2.2f,0f,0.0366f,1.1994f,0f,-0.8989f,2.3989f,-0.0733f,0f,-1.65f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone6) {transformation: [0f,0f,-2.2f,0f,0.0366f,1.1994f,0f,-0.9f,2.3989f,-0.0733f,0f,-1.725f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone20) {transformation: [-0.6707f,2.0953f,0f,0.0299f,-1.1429f,-0.3658f,0f,1.1347f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone19) {transformation: [1.4792f,1.6285f,0f,-1.2068f,-0.8883f,0.8068f,0f,0.522f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone18) {transformation: [2.1539f,0.448f,0f,-1.5428f,-0.2444f,1.1749f,0f,-0.3591f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone17) {transformation: [2.199f,-0.0672f,0f,-1.5125f,0.0366f,1.1994f,0f,-0.8989f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone16) {transformation: [2.199f,-0.0672f,0f,-1.5812f,0.0366f,1.1994f,0f,-0.9f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone15) {transformation: [0f,0f,2.2f,0f,-1.1429f,-0.3658f,0f,1.1347f,0.7317f,-2.2857f,0f,-0.0326f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone14) {transformation: [0f,0f,2.2f,0f,-0.8883f,0.8068f,0f,0.522f,-1.6137f,-1.7765f,0f,1.3165f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone13) {transformation: [0f,0f,2.2f,0f,-0.2444f,1.1749f,0f,-0.3591f,-2.3497f,-0.4887f,0f,1.683f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone12) {transformation: [0f,0f,2.2f,0f,0.0366f,1.1994f,0f,-0.8989f,-2.3989f,0.0733f,0f,1.65f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone11) {transformation: [0f,0f,2.2f,0f,0.0366f,1.1994f,0f,-0.9f,-2.3989f,0.0733f,0f,1.725f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}

playsound block.chain.break hostile @a ~1.25 ~ ~ 1 1
playsound block.chain.break hostile @a ~-1.25 ~ ~ 1 1
playsound block.chain.break hostile @a ~ ~ ~1.25 1 1
playsound block.chain.break hostile @a ~ ~ ~-1.25 1 1

execute as @n[tag=aj.chain_blast.root] at @s as @e[distance=..3] at @s run damage @s 0.25 ls_trip_and_magic:entity/ginunga/chain_blast
execute as @n[tag=aj.chain_blast.root] at @s run effect give @e[distance=..2] slowness 1 2 true