# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_bone5) {transformation: [1.1658f,-1.8657f,0f,-0.3227f,-1.0177f,-0.6359f,0f,1.18f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone4) {transformation: [-1.1982f,-1.8451f,0f,1.0785f,-1.0064f,0.6536f,0f,0.6837f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone3) {transformation: [-2.1094f,-0.6248f,0f,1.5471f,-0.3408f,1.1506f,0f,-0.1793f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone2) {transformation: [-2.1992f,0.0576f,0f,1.5125f,0.0314f,1.1996f,0f,-0.899f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone1) {transformation: [-2.1992f,0.0576f,0f,1.5813f,0.0314f,1.1996f,0f,-0.9f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone10) {transformation: [0f,0f,-2.2f,0f,-1.0177f,-0.6359f,0f,1.18f,-1.2718f,2.0353f,0f,0.352f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone9) {transformation: [0f,0f,-2.2f,0f,-1.0064f,0.6536f,0f,0.6837f,1.3071f,2.0128f,0f,-1.1765f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone8) {transformation: [0f,0f,-2.2f,0f,-0.3408f,1.1506f,0f,-0.1793f,2.3012f,0.6816f,0f,-1.6877f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone7) {transformation: [0f,0f,-2.2f,0f,0.0314f,1.1996f,0f,-0.899f,2.3992f,-0.0628f,0f,-1.65f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone6) {transformation: [0f,0f,-2.2f,0f,0.0314f,1.1996f,0f,-0.9f,2.3992f,-0.0628f,0f,-1.725f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone20) {transformation: [-1.1658f,1.8657f,0f,0.3227f,-1.0177f,-0.6359f,0f,1.18f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone19) {transformation: [1.1982f,1.8451f,0f,-1.0785f,-1.0064f,0.6536f,0f,0.6837f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone18) {transformation: [2.1094f,0.6248f,0f,-1.5471f,-0.3408f,1.1506f,0f,-0.1793f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone17) {transformation: [2.1992f,-0.0576f,0f,-1.5125f,0.0314f,1.1996f,0f,-0.899f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone16) {transformation: [2.1992f,-0.0576f,0f,-1.5812f,0.0314f,1.1996f,0f,-0.9f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone15) {transformation: [0f,0f,2.2f,0f,-1.0177f,-0.6359f,0f,1.18f,1.2718f,-2.0353f,0f,-0.352f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone14) {transformation: [0f,0f,2.2f,0f,-1.0064f,0.6536f,0f,0.6837f,-1.3071f,-2.0128f,0f,1.1765f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone13) {transformation: [0f,0f,2.2f,0f,-0.3408f,1.1506f,0f,-0.1793f,-2.3012f,-0.6816f,0f,1.6877f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone12) {transformation: [0f,0f,2.2f,0f,0.0314f,1.1996f,0f,-0.899f,-2.3992f,0.0628f,0f,1.65f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone11) {transformation: [0f,0f,2.2f,0f,0.0314f,1.1996f,0f,-0.9f,-2.3992f,0.0628f,0f,1.725f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}

playsound block.chain.break hostile @a ~1.25 ~ ~ 1 1
playsound block.chain.break hostile @a ~-1.25 ~ ~ 1 1
playsound block.chain.break hostile @a ~ ~ ~1.25 1 1
playsound block.chain.break hostile @a ~ ~ ~-1.25 1 1

execute as @n[tag=aj.chain_blast.root] at @s as @e[distance=..3] at @s run damage @s 0.25 ls_trip_and_magic:entity/ginunga/chain_blast
execute as @n[tag=aj.chain_blast.root] at @s run effect give @e[distance=..2] slowness 1 2 true