# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_bone5) {transformation: [2.1121f,-0.6156f,0f,-1.772f,-0.3358f,-1.1521f,0f,0.5041f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone4) {transformation: [1.622f,-1.4863f,0f,-0.6433f,-0.8107f,-0.8847f,0f,1.1759f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone3) {transformation: [-0.8419f,-2.0325f,0f,0.8811f,-1.1087f,0.4592f,0f,0.8315f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone2) {transformation: [-2.0325f,-0.8419f,0f,1.5125f,-0.4592f,1.1087f,0f,0f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone1) {transformation: [-2.2f,0f,0f,1.5813f,0f,1.2f,0f,-0.9f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone10) {transformation: [0f,0f,-2.2f,0f,-0.3358f,-1.1521f,0f,0.5041f,-2.3041f,0.6716f,0f,1.9331f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone9) {transformation: [0f,0f,-2.2f,0f,-0.8107f,-0.8847f,0f,1.1759f,-1.7695f,1.6214f,0f,0.7018f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone8) {transformation: [0f,0f,-2.2f,0f,-1.1087f,0.4592f,0f,0.8315f,0.9184f,2.2173f,0f,-0.9612f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone7) {transformation: [0f,0f,-2.2f,0f,-0.4592f,1.1087f,0f,0f,2.2173f,0.9184f,0f,-1.65f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone6) {transformation: [0f,0f,-2.2f,0f,0f,1.2f,0f,-0.9f,2.4f,0f,0f,-1.725f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone20) {transformation: [-2.1121f,0.6156f,0f,1.772f,-0.3358f,-1.1521f,0f,0.5041f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone19) {transformation: [-1.622f,1.4863f,0f,0.6433f,-0.8107f,-0.8847f,0f,1.1759f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone18) {transformation: [0.8419f,2.0325f,0f,-0.8811f,-1.1087f,0.4592f,0f,0.8315f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone17) {transformation: [2.0325f,0.8419f,0f,-1.5125f,-0.4592f,1.1087f,0f,0f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone16) {transformation: [2.2f,0f,0f,-1.5812f,0f,1.2f,0f,-0.9f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone15) {transformation: [0f,0f,2.2f,0f,-0.3358f,-1.1521f,0f,0.5041f,2.3041f,-0.6716f,0f,-1.9331f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone14) {transformation: [0f,0f,2.2f,0f,-0.8107f,-0.8847f,0f,1.1759f,1.7695f,-1.6214f,0f,-0.7018f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone13) {transformation: [0f,0f,2.2f,0f,-1.1087f,0.4592f,0f,0.8315f,-0.9184f,-2.2173f,0f,0.9612f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone12) {transformation: [0f,0f,2.2f,0f,-0.4592f,1.1087f,0f,0f,-2.2173f,-0.9184f,0f,1.65f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone11) {transformation: [0f,0f,2.2f,0f,0f,1.2f,0f,-0.9f,-2.4f,0f,0f,1.725f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}

playsound block.chain.break hostile @a ~1.25 ~ ~ 1 1
playsound block.chain.break hostile @a ~-1.25 ~ ~ 1 1
playsound block.chain.break hostile @a ~ ~ ~1.25 1 1
playsound block.chain.break hostile @a ~ ~ ~-1.25 1 1

execute as @n[tag=aj.chain_blast.root] at @s as @e[distance=..3] at @s run damage @s 0.25 ch_trip_and_magic:entity/ginunga/chain_blast
execute as @n[tag=aj.chain_blast.root] at @s run effect give @e[distance=..2] slowness 1 2 true