# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_bone5) {transformation: [1.9939f,-0.9298f,0f,-2.3573f,-0.5071f,-1.0876f,0f,0.42f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone4) {transformation: [1.622f,-1.4863f,0f,-1.2286f,-0.8107f,-0.8847f,0f,1.0918f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone3) {transformation: [-0.3252f,-2.1758f,0f,0.4033f,-1.1868f,0.1774f,0f,0.9588f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone2) {transformation: [-1.8758f,-1.1495f,0f,1.2654f,-0.627f,1.0232f,0f,0.1914f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone1) {transformation: [-2.1932f,-0.1726f,0f,1.4634f,-0.0942f,1.1963f,0f,-0.7029f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone10) {transformation: [0f,0f,-2.2f,0f,-0.5071f,-1.0876f,0f,0.42f,-2.1751f,1.0143f,0f,2.5716f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone9) {transformation: [0f,0f,-2.2f,0f,-0.8107f,-0.8847f,0f,1.0918f,-1.7695f,1.6214f,0f,1.3403f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone8) {transformation: [0f,0f,-2.2f,0f,-1.1868f,0.1774f,0f,0.9588f,0.3547f,2.3736f,0f,-0.4399f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone7) {transformation: [0f,0f,-2.2f,0f,-0.627f,1.0232f,0f,0.1914f,2.0463f,1.254f,0f,-1.3804f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone6) {transformation: [0f,0f,-2.2f,0f,-0.0942f,1.1963f,0f,-0.7029f,2.3926f,0.1883f,0f,-1.5964f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone20) {transformation: [-1.9939f,0.9298f,0f,2.3573f,-0.5071f,-1.0876f,0f,0.42f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone19) {transformation: [-1.622f,1.4863f,0f,1.2286f,-0.8107f,-0.8847f,0f,1.0918f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone18) {transformation: [0.3252f,2.1758f,0f,-0.4033f,-1.1868f,0.1774f,0f,0.9588f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone17) {transformation: [1.8758f,1.1495f,0f,-1.2654f,-0.627f,1.0232f,0f,0.1914f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone16) {transformation: [2.1932f,0.1726f,0f,-1.4634f,-0.0942f,1.1963f,0f,-0.7029f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone15) {transformation: [0f,0f,2.2f,0f,-0.5071f,-1.0876f,0f,0.42f,2.1751f,-1.0143f,0f,-2.5716f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone14) {transformation: [0f,0f,2.2f,0f,-0.8107f,-0.8847f,0f,1.0918f,1.7695f,-1.6214f,0f,-1.3403f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone13) {transformation: [0f,0f,2.2f,0f,-1.1868f,0.1774f,0f,0.9588f,-0.3547f,-2.3736f,0f,0.4399f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone12) {transformation: [0f,0f,2.2f,0f,-0.627f,1.0232f,0f,0.1914f,-2.0463f,-1.254f,0f,1.3804f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone11) {transformation: [0f,0f,2.2f,0f,-0.0942f,1.1963f,0f,-0.7029f,-2.3926f,-0.1883f,0f,1.5964f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}

playsound block.chain.break hostile @a ~1.25 ~ ~ 1 1
playsound block.chain.break hostile @a ~-1.25 ~ ~ 1 1
playsound block.chain.break hostile @a ~ ~ ~1.25 1 1
playsound block.chain.break hostile @a ~ ~ ~-1.25 1 1

execute as @n[tag=aj.chain_blast.root] at @s as @e[distance=..3] at @s run damage @s 0.25 ch_trip_and_magic:entity/ginunga/chain_blast
execute as @n[tag=aj.chain_blast.root] at @s run effect give @e[distance=..2] slowness 1 2 true