# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_bone5) {transformation: [1.622f,-1.4863f,0f,-3.163f,-0.8107f,-0.8847f,0f,0.17f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone4) {transformation: [1.622f,-1.4863f,0f,-2.0344f,-0.8107f,-0.8847f,0f,0.8419f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone3) {transformation: [0.7344f,-2.0738f,0f,-0.479f,-1.1312f,-0.4006f,0f,1.1423f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone2) {transformation: [-1.4288f,-1.6729f,0f,0.7756f,-0.9125f,0.7793f,0f,0.5578f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone1) {transformation: [-2.1392f,-0.5136f,0f,1.2277f,-0.2801f,1.1668f,0f,-0.3086f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone10) {transformation: [0f,0f,-2.2f,0f,-0.8107f,-0.8847f,0f,0.17f,-1.7695f,1.6214f,0f,3.4506f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone9) {transformation: [0f,0f,-2.2f,0f,-0.8107f,-0.8847f,0f,0.8419f,-1.7695f,1.6214f,0f,2.2193f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone8) {transformation: [0f,0f,-2.2f,0f,-1.1312f,-0.4006f,0f,1.1423f,-0.8011f,2.2623f,0f,0.5226f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone7) {transformation: [0f,0f,-2.2f,0f,-0.9125f,0.7793f,0f,0.5578f,1.5587f,1.825f,0f,-0.8462f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone6) {transformation: [0f,0f,-2.2f,0f,-0.2801f,1.1668f,0f,-0.3086f,2.3337f,0.5603f,0f,-1.3393f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone20) {transformation: [-1.622f,1.4863f,0f,3.163f,-0.8107f,-0.8847f,0f,0.17f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone19) {transformation: [-1.622f,1.4863f,0f,2.0344f,-0.8107f,-0.8847f,0f,0.8419f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone18) {transformation: [-0.7344f,2.0738f,0f,0.479f,-1.1312f,-0.4006f,0f,1.1423f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone17) {transformation: [1.4288f,1.6729f,0f,-0.7756f,-0.9125f,0.7793f,0f,0.5578f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone16) {transformation: [2.1392f,0.5136f,0f,-1.2277f,-0.2801f,1.1668f,0f,-0.3086f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone15) {transformation: [0f,0f,2.2f,0f,-0.8107f,-0.8847f,0f,0.17f,1.7695f,-1.6214f,0f,-3.4506f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone14) {transformation: [0f,0f,2.2f,0f,-0.8107f,-0.8847f,0f,0.8419f,1.7695f,-1.6214f,0f,-2.2193f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone13) {transformation: [0f,0f,2.2f,0f,-1.1312f,-0.4006f,0f,1.1423f,0.8011f,-2.2623f,0f,-0.5226f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone12) {transformation: [0f,0f,2.2f,0f,-0.9125f,0.7793f,0f,0.5578f,-1.5587f,-1.825f,0f,0.8462f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone11) {transformation: [0f,0f,2.2f,0f,-0.2801f,1.1668f,0f,-0.3086f,-2.3337f,-0.5603f,0f,1.3393f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}

playsound block.chain.break hostile @a ~1.25 ~ ~ 1 1
playsound block.chain.break hostile @a ~-1.25 ~ ~ 1 1
playsound block.chain.break hostile @a ~ ~ ~1.25 1 1
playsound block.chain.break hostile @a ~ ~ ~-1.25 1 1

execute as @n[tag=aj.chain_blast.root] at @s as @e[distance=..3] at @s run damage @s 0.25 ls_trip_and_magic:entity/ginunga/chain_blast
execute as @n[tag=aj.chain_blast.root] at @s run effect give @e[distance=..2] slowness 1 2 true