# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_bone5) {transformation: [1.622f,-1.4863f,0f,-3.3769f,-0.8107f,-0.8847f,0f,0.0346f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone4) {transformation: [1.622f,-1.4863f,0f,-2.2482f,-0.8107f,-0.8847f,0f,0.7064f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone3) {transformation: [1.2143f,-1.8345f,0f,-0.8723f,-1.0007f,-0.6623f,0f,1.2032f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone2) {transformation: [-1.1495f,-1.8758f,0f,0.5346f,-1.0232f,0.627f,0f,0.7329f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone1) {transformation: [-2.0923f,-0.6798f,0f,1.1098f,-0.3708f,1.1413f,0f,-0.1114f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone10) {transformation: [0f,0f,-2.2f,0f,-0.8107f,-0.8847f,0f,0.0346f,-1.7695f,1.6214f,0f,3.6839f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone9) {transformation: [0f,0f,-2.2f,0f,-0.8107f,-0.8847f,0f,0.7064f,-1.7695f,1.6214f,0f,2.4526f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone8) {transformation: [0f,0f,-2.2f,0f,-1.0007f,-0.6623f,0f,1.2032f,-1.3246f,2.0013f,0f,0.9516f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone7) {transformation: [0f,0f,-2.2f,0f,-1.0232f,0.627f,0f,0.7329f,1.254f,2.0463f,0f,-0.5832f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone6) {transformation: [0f,0f,-2.2f,0f,-0.3708f,1.1413f,0f,-0.1114f,2.2825f,0.7416f,0f,-1.2107f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone20) {transformation: [-1.622f,1.4863f,0f,3.3769f,-0.8107f,-0.8847f,0f,0.0346f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone19) {transformation: [-1.622f,1.4863f,0f,2.2482f,-0.8107f,-0.8847f,0f,0.7064f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone18) {transformation: [-1.2143f,1.8345f,0f,0.8723f,-1.0007f,-0.6623f,0f,1.2032f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone17) {transformation: [1.1495f,1.8758f,0f,-0.5346f,-1.0232f,0.627f,0f,0.7329f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone16) {transformation: [2.0923f,0.6798f,0f,-1.1098f,-0.3708f,1.1413f,0f,-0.1114f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone15) {transformation: [0f,0f,2.2f,0f,-0.8107f,-0.8847f,0f,0.0346f,1.7695f,-1.6214f,0f,-3.6839f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone14) {transformation: [0f,0f,2.2f,0f,-0.8107f,-0.8847f,0f,0.7064f,1.7695f,-1.6214f,0f,-2.4526f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone13) {transformation: [0f,0f,2.2f,0f,-1.0007f,-0.6623f,0f,1.2032f,1.3246f,-2.0013f,0f,-0.9516f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone12) {transformation: [0f,0f,2.2f,0f,-1.0232f,0.627f,0f,0.7329f,-1.254f,-2.0463f,0f,0.5832f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone11) {transformation: [0f,0f,2.2f,0f,-0.3708f,1.1413f,0f,-0.1114f,-2.2825f,-0.7416f,0f,1.2107f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}

playsound block.chain.break hostile @a ~1.25 ~ ~ 1 1
playsound block.chain.break hostile @a ~-1.25 ~ ~ 1 1
playsound block.chain.break hostile @a ~ ~ ~1.25 1 1
playsound block.chain.break hostile @a ~ ~ ~-1.25 1 1

execute as @n[tag=aj.chain_blast.root] at @s as @e[distance=..3] at @s run damage @s 0.25 ls_trip_and_magic:entity/ginunga/chain_blast
execute as @n[tag=aj.chain_blast.root] at @s run effect give @e[distance=..2] slowness 1 2 true