# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_bone5) {transformation: [1.7037f,-1.392f,0f,-3.8784f,-0.7592f,-0.9293f,0f,-0.3241f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone4) {transformation: [1.7037f,-1.392f,0f,-2.8214f,-0.7592f,-0.9293f,0f,0.3816f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone3) {transformation: [1.7037f,-1.392f,0f,-1.7774f,-0.7592f,-0.9293f,0f,1.0785f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone2) {transformation: [-0.2013f,-2.1908f,0f,-0.1343f,-1.195f,0.1098f,0f,0.9962f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone1) {transformation: [-1.7966f,-1.2697f,0f,0.8741f,-0.6926f,0.98f,0f,0.2829f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone10) {transformation: [0f,0f,-2.2f,0f,-0.7592f,-0.9293f,0f,-0.3241f,-1.8585f,1.5185f,0f,4.231f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone9) {transformation: [0f,0f,-2.2f,0f,-0.7592f,-0.9293f,0f,0.3816f,-1.8585f,1.5185f,0f,3.0779f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone8) {transformation: [0f,0f,-2.2f,0f,-0.7592f,-0.9293f,0f,1.0785f,-1.8585f,1.5185f,0f,1.939f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone7) {transformation: [0f,0f,-2.2f,0f,-1.195f,0.1098f,0f,0.9962f,0.2196f,2.3899f,0f,0.1465f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone6) {transformation: [0f,0f,-2.2f,0f,-0.6926f,0.98f,0f,0.2829f,1.9599f,1.3851f,0f,-0.9536f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone20) {transformation: [-1.7037f,1.392f,0f,3.8784f,-0.7592f,-0.9293f,0f,-0.3241f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone19) {transformation: [-1.7037f,1.392f,0f,2.8214f,-0.7592f,-0.9293f,0f,0.3816f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone18) {transformation: [-1.7037f,1.392f,0f,1.7774f,-0.7592f,-0.9293f,0f,1.0785f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone17) {transformation: [0.2013f,2.1908f,0f,0.1343f,-1.195f,0.1098f,0f,0.9962f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone16) {transformation: [1.7966f,1.2697f,0f,-0.8741f,-0.6926f,0.98f,0f,0.2829f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone15) {transformation: [0f,0f,2.2f,0f,-0.7592f,-0.9293f,0f,-0.3241f,1.8585f,-1.5185f,0f,-4.231f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone14) {transformation: [0f,0f,2.2f,0f,-0.7592f,-0.9293f,0f,0.3816f,1.8585f,-1.5185f,0f,-3.0779f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone13) {transformation: [0f,0f,2.2f,0f,-0.7592f,-0.9293f,0f,1.0785f,1.8585f,-1.5185f,0f,-1.939f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone12) {transformation: [0f,0f,2.2f,0f,-1.195f,0.1098f,0f,0.9962f,-0.2196f,-2.3899f,0f,-0.1465f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone11) {transformation: [0f,0f,2.2f,0f,-0.6926f,0.98f,0f,0.2829f,-1.9599f,-1.3851f,0f,0.9536f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}

playsound block.chain.break hostile @a ~1.25 ~ ~ 1 1
playsound block.chain.break hostile @a ~-1.25 ~ ~ 1 1
playsound block.chain.break hostile @a ~ ~ ~1.25 1 1
playsound block.chain.break hostile @a ~ ~ ~-1.25 1 1

execute as @n[tag=aj.chain_blast.root] at @s as @e[distance=..3] at @s run damage @s 0.25 ch_trip_and_magic:entity/ginunga/chain_blast
execute as @n[tag=aj.chain_blast.root] at @s run effect give @e[distance=..2] slowness 1 2 true