# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_bone5) {transformation: [1.7798f,-1.2931f,0f,-4.0817f,-0.7053f,-0.9708f,0f,-0.5981f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone4) {transformation: [1.7798f,-1.2931f,0f,-3.0997f,-0.7053f,-0.9708f,0f,0.1391f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone3) {transformation: [1.7798f,-1.2931f,0f,-2.1299f,-0.7053f,-0.9708f,0f,0.8672f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone2) {transformation: [0.4574f,-2.1519f,0f,-0.5159f,-1.1738f,-0.2495f,0f,1.0543f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone1) {transformation: [-1.4721f,-1.6349f,0f,0.7563f,-0.8918f,0.803f,0f,0.48f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone10) {transformation: [0f,0f,-2.2f,0f,-0.7053f,-0.9708f,0f,-0.5981f,-1.9416f,1.4107f,0f,4.4528f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone9) {transformation: [0f,0f,-2.2f,0f,-0.7053f,-0.9708f,0f,0.1391f,-1.9416f,1.4107f,0f,3.3815f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone8) {transformation: [0f,0f,-2.2f,0f,-0.7053f,-0.9708f,0f,0.8672f,-1.9416f,1.4107f,0f,2.3235f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone7) {transformation: [0f,0f,-2.2f,0f,-1.1738f,-0.2495f,0f,1.0543f,-0.499f,2.3476f,0f,0.5628f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone6) {transformation: [0f,0f,-2.2f,0f,-0.8918f,0.803f,0f,0.48f,1.6059f,1.7835f,0f,-0.825f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone20) {transformation: [-1.7798f,1.2931f,0f,4.0817f,-0.7053f,-0.9708f,0f,-0.5981f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone19) {transformation: [-1.7798f,1.2931f,0f,3.0997f,-0.7053f,-0.9708f,0f,0.1391f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone18) {transformation: [-1.7798f,1.2931f,0f,2.1299f,-0.7053f,-0.9708f,0f,0.8672f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone17) {transformation: [-0.4574f,2.1519f,0f,0.5159f,-1.1738f,-0.2495f,0f,1.0543f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone16) {transformation: [1.4721f,1.6349f,0f,-0.7563f,-0.8918f,0.803f,0f,0.48f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone15) {transformation: [0f,0f,2.2f,0f,-0.7053f,-0.9708f,0f,-0.5981f,1.9416f,-1.4107f,0f,-4.4528f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone14) {transformation: [0f,0f,2.2f,0f,-0.7053f,-0.9708f,0f,0.1391f,1.9416f,-1.4107f,0f,-3.3815f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone13) {transformation: [0f,0f,2.2f,0f,-0.7053f,-0.9708f,0f,0.8672f,1.9416f,-1.4107f,0f,-2.3235f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone12) {transformation: [0f,0f,2.2f,0f,-1.1738f,-0.2495f,0f,1.0543f,0.499f,-2.3476f,0f,-0.5628f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone11) {transformation: [0f,0f,2.2f,0f,-0.8918f,0.803f,0f,0.48f,-1.6059f,-1.7835f,0f,0.825f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}

playsound block.chain.break hostile @a ~1.25 ~ ~ 1 1
playsound block.chain.break hostile @a ~-1.25 ~ ~ 1 1
playsound block.chain.break hostile @a ~ ~ ~1.25 1 1
playsound block.chain.break hostile @a ~ ~ ~-1.25 1 1

execute as @n[tag=aj.chain_blast.root] at @s as @e[distance=..3] at @s run damage @s 0.25 ls_trip_and_magic:entity/ginunga/chain_blast
execute as @n[tag=aj.chain_blast.root] at @s run effect give @e[distance=..2] slowness 1 2 true