# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_bone5) {transformation: [1.8503f,-1.1901f,0f,-4.1074f,-0.6492f,-1.0092f,0f,-0.9953f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone4) {transformation: [1.8503f,-1.1901f,0f,-3.2036f,-0.6492f,-1.0092f,0f,-0.2289f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone3) {transformation: [1.8503f,-1.1901f,0f,-2.311f,-0.6492f,-1.0092f,0f,0.528f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone2) {transformation: [1.075f,-1.9195f,0f,-0.8714f,-1.047f,-0.5863f,0f,0.9678f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone1) {transformation: [-1.075f,-1.9195f,0f,0.6018f,-1.047f,0.5863f,0f,0.5607f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone10) {transformation: [0f,0f,-2.2f,0f,-0.6492f,-1.0092f,0f,-0.9953f,-2.0185f,1.2983f,0f,4.4808f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone9) {transformation: [0f,0f,-2.2f,0f,-0.6492f,-1.0092f,0f,-0.2289f,-2.0185f,1.2983f,0f,3.4949f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone8) {transformation: [0f,0f,-2.2f,0f,-0.6492f,-1.0092f,0f,0.528f,-2.0185f,1.2983f,0f,2.5211f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone7) {transformation: [0f,0f,-2.2f,0f,-1.047f,-0.5863f,0f,0.9678f,-1.1727f,2.094f,0f,0.9506f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone6) {transformation: [0f,0f,-2.2f,0f,-1.047f,0.5863f,0f,0.5607f,1.1727f,2.094f,0f,-0.6565f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone20) {transformation: [-1.8503f,1.1901f,0f,4.1074f,-0.6492f,-1.0092f,0f,-0.9953f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone19) {transformation: [-1.8503f,1.1901f,0f,3.2036f,-0.6492f,-1.0092f,0f,-0.2289f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone18) {transformation: [-1.8503f,1.1901f,0f,2.311f,-0.6492f,-1.0092f,0f,0.528f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone17) {transformation: [-1.075f,1.9195f,0f,0.8714f,-1.047f,-0.5863f,0f,0.9678f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone16) {transformation: [1.075f,1.9195f,0f,-0.6018f,-1.047f,0.5863f,0f,0.5607f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone15) {transformation: [0f,0f,2.2f,0f,-0.6492f,-1.0092f,0f,-0.9953f,2.0185f,-1.2983f,0f,-4.4808f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone14) {transformation: [0f,0f,2.2f,0f,-0.6492f,-1.0092f,0f,-0.2289f,2.0185f,-1.2983f,0f,-3.4949f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone13) {transformation: [0f,0f,2.2f,0f,-0.6492f,-1.0092f,0f,0.528f,2.0185f,-1.2983f,0f,-2.5211f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone12) {transformation: [0f,0f,2.2f,0f,-1.047f,-0.5863f,0f,0.9678f,1.1727f,-2.094f,0f,-0.9506f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone11) {transformation: [0f,0f,2.2f,0f,-1.047f,0.5863f,0f,0.5607f,-1.1727f,-2.094f,0f,0.6565f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}

playsound block.chain.break hostile @a ~1.25 ~ ~ 1 1
playsound block.chain.break hostile @a ~-1.25 ~ ~ 1 1
playsound block.chain.break hostile @a ~ ~ ~1.25 1 1
playsound block.chain.break hostile @a ~ ~ ~-1.25 1 1

execute as @n[tag=aj.chain_blast.root] at @s as @e[distance=..3] at @s run damage @s 0.25 ls_trip_and_magic:entity/ginunga/chain_blast
execute as @n[tag=aj.chain_blast.root] at @s run effect give @e[distance=..2] slowness 1 2 true