# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_bone5) {transformation: [1.9148f,-1.0833f,0f,-3.9252f,-0.5909f,-1.0444f,0f,-1.3681f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone4) {transformation: [1.9148f,-1.0833f,0f,-3.1025f,-0.5909f,-1.0444f,0f,-0.575f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone3) {transformation: [1.9148f,-1.0833f,0f,-2.29f,-0.5909f,-1.0444f,0f,0.2083f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone2) {transformation: [1.5958f,-1.5144f,0f,-1.1542f,-0.826f,-0.8704f,0f,0.8612f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone1) {transformation: [-0.6248f,-2.1094f,0f,0.4473f,-1.1506f,0.3408f,0f,0.6415f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone10) {transformation: [0f,0f,-2.2f,0f,-0.5909f,-1.0444f,0f,-1.3681f,-2.0889f,1.1818f,0f,4.282f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone9) {transformation: [0f,0f,-2.2f,0f,-0.5909f,-1.0444f,0f,-0.575f,-2.0889f,1.1818f,0f,3.3846f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone8) {transformation: [0f,0f,-2.2f,0f,-0.5909f,-1.0444f,0f,0.2083f,-2.0889f,1.1818f,0f,2.4982f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone7) {transformation: [0f,0f,-2.2f,0f,-0.826f,-0.8704f,0f,0.8612f,-1.7409f,1.6521f,0f,1.2592f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone6) {transformation: [0f,0f,-2.2f,0f,-1.1506f,0.3408f,0f,0.6415f,0.6816f,2.3012f,0f,-0.488f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone20) {transformation: [-1.9148f,1.0833f,0f,3.9252f,-0.5909f,-1.0444f,0f,-1.3681f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone19) {transformation: [-1.9148f,1.0833f,0f,3.1025f,-0.5909f,-1.0444f,0f,-0.575f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone18) {transformation: [-1.9148f,1.0833f,0f,2.29f,-0.5909f,-1.0444f,0f,0.2083f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone17) {transformation: [-1.5958f,1.5144f,0f,1.1542f,-0.826f,-0.8704f,0f,0.8612f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone16) {transformation: [0.6248f,2.1094f,0f,-0.4473f,-1.1506f,0.3408f,0f,0.6415f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone15) {transformation: [0f,0f,2.2f,0f,-0.5909f,-1.0444f,0f,-1.3681f,2.0889f,-1.1818f,0f,-4.282f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone14) {transformation: [0f,0f,2.2f,0f,-0.5909f,-1.0444f,0f,-0.575f,2.0889f,-1.1818f,0f,-3.3846f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone13) {transformation: [0f,0f,2.2f,0f,-0.5909f,-1.0444f,0f,0.2083f,2.0889f,-1.1818f,0f,-2.4982f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone12) {transformation: [0f,0f,2.2f,0f,-0.826f,-0.8704f,0f,0.8612f,1.7409f,-1.6521f,0f,-1.2592f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone11) {transformation: [0f,0f,2.2f,0f,-1.1506f,0.3408f,0f,0.6415f,-0.6816f,-2.3012f,0f,0.488f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}

playsound block.chain.break hostile @a ~1.25 ~ ~ 1 1
playsound block.chain.break hostile @a ~-1.25 ~ ~ 1 1
playsound block.chain.break hostile @a ~ ~ ~1.25 1 1
playsound block.chain.break hostile @a ~ ~ ~-1.25 1 1

execute as @n[tag=aj.chain_blast.root] at @s as @e[distance=..3] at @s run damage @s 0.25 ch_trip_and_magic:entity/ginunga/chain_blast
execute as @n[tag=aj.chain_blast.root] at @s run effect give @e[distance=..2] slowness 1 2 true