# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_bone5) {transformation: [1.9731f,-0.973f,0f,-3.5565f,-0.5307f,-1.0762f,0f,-1.688f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone4) {transformation: [1.9731f,-0.973f,0f,-2.8176f,-0.5307f,-1.0762f,0f,-0.8707f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone3) {transformation: [1.9731f,-0.973f,0f,-2.0879f,-0.5307f,-1.0762f,0f,-0.0635f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone2) {transformation: [1.9731f,-0.973f,0f,-1.3581f,-0.5307f,-1.0762f,0f,0.7437f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone1) {transformation: [-0.1439f,-2.1953f,0f,0.2929f,-1.1974f,0.0785f,0f,0.7223f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone10) {transformation: [0f,0f,-2.2f,0f,-0.5307f,-1.0762f,0f,-1.688f,-2.1525f,1.0615f,0f,3.8799f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone9) {transformation: [0f,0f,-2.2f,0f,-0.5307f,-1.0762f,0f,-0.8707f,-2.1525f,1.0615f,0f,3.0738f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone8) {transformation: [0f,0f,-2.2f,0f,-0.5307f,-1.0762f,0f,-0.0635f,-2.1525f,1.0615f,0f,2.2777f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone7) {transformation: [0f,0f,-2.2f,0f,-0.5307f,-1.0762f,0f,0.7437f,-2.1525f,1.0615f,0f,1.4816f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone6) {transformation: [0f,0f,-2.2f,0f,-1.1974f,0.0785f,0f,0.7223f,0.157f,2.3949f,0f,-0.3195f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone20) {transformation: [-1.9731f,0.973f,0f,3.5565f,-0.5307f,-1.0762f,0f,-1.688f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone19) {transformation: [-1.9731f,0.973f,0f,2.8176f,-0.5307f,-1.0762f,0f,-0.8707f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone18) {transformation: [-1.9731f,0.973f,0f,2.0879f,-0.5307f,-1.0762f,0f,-0.0635f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone17) {transformation: [-1.9731f,0.973f,0f,1.3581f,-0.5307f,-1.0762f,0f,0.7437f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone16) {transformation: [0.1439f,2.1953f,0f,-0.2929f,-1.1974f,0.0785f,0f,0.7223f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone15) {transformation: [0f,0f,2.2f,0f,-0.5307f,-1.0762f,0f,-1.688f,2.1525f,-1.0615f,0f,-3.8799f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone14) {transformation: [0f,0f,2.2f,0f,-0.5307f,-1.0762f,0f,-0.8707f,2.1525f,-1.0615f,0f,-3.0738f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone13) {transformation: [0f,0f,2.2f,0f,-0.5307f,-1.0762f,0f,-0.0635f,2.1525f,-1.0615f,0f,-2.2777f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone12) {transformation: [0f,0f,2.2f,0f,-0.5307f,-1.0762f,0f,0.7437f,2.1525f,-1.0615f,0f,-1.4816f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone11) {transformation: [0f,0f,2.2f,0f,-1.1974f,0.0785f,0f,0.7223f,-0.157f,-2.3949f,0f,0.3195f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}

playsound block.chain.break hostile @a ~1.25 ~ ~ 1 1
playsound block.chain.break hostile @a ~-1.25 ~ ~ 1 1
playsound block.chain.break hostile @a ~ ~ ~1.25 1 1
playsound block.chain.break hostile @a ~ ~ ~-1.25 1 1

execute as @n[tag=aj.chain_blast.root] at @s as @e[distance=..3] at @s run damage @s 0.25 ch_trip_and_magic:entity/ginunga/chain_blast
execute as @n[tag=aj.chain_blast.root] at @s run effect give @e[distance=..2] slowness 1 2 true