# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_bone5) {transformation: [1.9334f,-1.0497f,0f,-4.8542f,-0.5726f,-1.0546f,0f,-2.6795f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone4) {transformation: [1.9334f,-1.0497f,0f,-4.0571f,-0.5726f,-1.0546f,0f,-1.8786f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone3) {transformation: [1.9334f,-1.0497f,0f,-3.2698f,-0.5726f,-1.0546f,0f,-1.0877f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone2) {transformation: [1.9334f,-1.0497f,0f,-2.4825f,-0.5726f,-1.0546f,0f,-0.2968f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone1) {transformation: [1.2461f,-1.8131f,0f,-1.1616f,-0.989f,-0.6797f,0f,0.2439f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone10) {transformation: [0f,0f,-2.2f,0f,-0.5726f,-1.0546f,0f,-2.6795f,-2.1092f,1.1452f,0f,5.2955f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone9) {transformation: [0f,0f,-2.2f,0f,-0.5726f,-1.0546f,0f,-1.8786f,-2.1092f,1.1452f,0f,4.4259f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone8) {transformation: [0f,0f,-2.2f,0f,-0.5726f,-1.0546f,0f,-1.0877f,-2.1092f,1.1452f,0f,3.567f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone7) {transformation: [0f,0f,-2.2f,0f,-0.5726f,-1.0546f,0f,-0.2968f,-2.1092f,1.1452f,0f,2.7081f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone6) {transformation: [0f,0f,-2.2f,0f,-0.989f,-0.6797f,0f,0.2439f,-1.3594f,1.9779f,0f,1.2672f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone20) {transformation: [-1.9334f,1.0497f,0f,4.8542f,-0.5726f,-1.0546f,0f,-2.6795f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone19) {transformation: [-1.9334f,1.0497f,0f,4.0571f,-0.5726f,-1.0546f,0f,-1.8786f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone18) {transformation: [-1.9334f,1.0497f,0f,3.2698f,-0.5726f,-1.0546f,0f,-1.0877f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone17) {transformation: [-1.9334f,1.0497f,0f,2.4825f,-0.5726f,-1.0546f,0f,-0.2968f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone16) {transformation: [-1.2461f,1.8131f,0f,1.1616f,-0.989f,-0.6797f,0f,0.2439f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone15) {transformation: [0f,0f,2.2f,0f,-0.5726f,-1.0546f,0f,-2.6795f,2.1092f,-1.1452f,0f,-5.2955f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone14) {transformation: [0f,0f,2.2f,0f,-0.5726f,-1.0546f,0f,-1.8786f,2.1092f,-1.1452f,0f,-4.4259f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone13) {transformation: [0f,0f,2.2f,0f,-0.5726f,-1.0546f,0f,-1.0877f,2.1092f,-1.1452f,0f,-3.567f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone12) {transformation: [0f,0f,2.2f,0f,-0.5726f,-1.0546f,0f,-0.2968f,2.1092f,-1.1452f,0f,-2.7081f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone11) {transformation: [0f,0f,2.2f,0f,-0.989f,-0.6797f,0f,0.2439f,1.3594f,-1.9779f,0f,-1.2672f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}

playsound block.chain.break hostile @a ~1.25 ~ ~ 1 1
playsound block.chain.break hostile @a ~-1.25 ~ ~ 1 1
playsound block.chain.break hostile @a ~ ~ ~1.25 1 1
playsound block.chain.break hostile @a ~ ~ ~-1.25 1 1

execute as @n[tag=aj.chain_blast.root] at @s as @e[distance=..3] at @s run damage @s 0.25 ch_trip_and_magic:entity/ginunga/chain_blast
execute as @n[tag=aj.chain_blast.root] at @s run effect give @e[distance=..2] slowness 1 2 true