# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_blast1) {transformation: [0f,0f,-2.2f,0.0688f,0f,0.6f,0f,0.3f,2.4f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_blast) {transformation: [-2.2f,0f,0f,0f,0f,0.6f,0f,0f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone5) {transformation: [1.9195f,-1.075f,0f,-5.1447f,-0.5863f,-1.047f,0f,-2.9675f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone4) {transformation: [1.9195f,-1.075f,0f,-4.3284f,-0.5863f,-1.047f,0f,-2.1724f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone3) {transformation: [1.9195f,-1.075f,0f,-3.5222f,-0.5863f,-1.047f,0f,-1.3871f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone2) {transformation: [1.9195f,-1.075f,0f,-2.716f,-0.5863f,-1.047f,0f,-0.6019f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone1) {transformation: [1.6155f,-1.4934f,0f,-1.6464f,-0.8146f,-0.8812f,0f,0.0845f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone10) {transformation: [0f,0f,-2.2f,0f,-0.5863f,-1.047f,0f,-2.9675f,-2.094f,1.1727f,0f,5.6124f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone9) {transformation: [0f,0f,-2.2f,0f,-0.5863f,-1.047f,0f,-2.1724f,-2.094f,1.1727f,0f,4.7219f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone8) {transformation: [0f,0f,-2.2f,0f,-0.5863f,-1.047f,0f,-1.3871f,-2.094f,1.1727f,0f,3.8424f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone7) {transformation: [0f,0f,-2.2f,0f,-0.5863f,-1.047f,0f,-0.6019f,-2.094f,1.1727f,0f,2.9629f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone6) {transformation: [0f,0f,-2.2f,0f,-0.8146f,-0.8812f,0f,0.0845f,-1.7624f,1.6291f,0f,1.7961f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone20) {transformation: [-1.9195f,1.075f,0f,5.1447f,-0.5863f,-1.047f,0f,-2.9675f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone19) {transformation: [-1.9195f,1.075f,0f,4.3284f,-0.5863f,-1.047f,0f,-2.1724f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone18) {transformation: [-1.9195f,1.075f,0f,3.5222f,-0.5863f,-1.047f,0f,-1.3871f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone17) {transformation: [-1.9195f,1.075f,0f,2.716f,-0.5863f,-1.047f,0f,-0.6019f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone16) {transformation: [-1.6155f,1.4934f,0f,1.6464f,-0.8146f,-0.8812f,0f,0.0845f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone15) {transformation: [0f,0f,2.2f,0f,-0.5863f,-1.047f,0f,-2.9675f,2.094f,-1.1727f,0f,-5.6124f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone14) {transformation: [0f,0f,2.2f,0f,-0.5863f,-1.047f,0f,-2.1724f,2.094f,-1.1727f,0f,-4.7219f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone13) {transformation: [0f,0f,2.2f,0f,-0.5863f,-1.047f,0f,-1.3871f,2.094f,-1.1727f,0f,-3.8424f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone12) {transformation: [0f,0f,2.2f,0f,-0.5863f,-1.047f,0f,-0.6019f,2.094f,-1.1727f,0f,-2.9629f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone11) {transformation: [0f,0f,2.2f,0f,-0.8146f,-0.8812f,0f,0.0845f,1.7624f,-1.6291f,0f,-1.7961f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute as @n[tag=aj.chain_blast.root] at @s positioned ~0.5 ~0.25 ~ run function ch_effect_temp:vfx/ginga/explotion/play
execute as @n[tag=aj.chain_blast.root] at @s positioned ~0.5 ~0.25 ~0.25 run function ch_effect_temp:vfx/ginga/explotion/play
execute as @n[tag=aj.chain_blast.root] at @s positioned ~ ~0.25 ~0.5 run function ch_effect_temp:vfx/ginga/explotion/play
execute as @n[tag=aj.chain_blast.root] at @s positioned ~0.25 ~0.25 ~0.75 run function ch_effect_temp:vfx/ginga/explotion/play
execute as @n[tag=aj.chain_blast.root] at @s positioned ~-0.5 ~0.25 ~-0.5 run function ch_effect_temp:vfx/ginga/explotion/play
execute as @n[tag=aj.chain_blast.root] at @s positioned ~ ~0.25 ~ run function ch_effect_temp:vfx/ginga/explotion/play
execute as @n[tag=aj.chain_blast.root] at @s positioned ~0.5 ~0.75 ~0.25 run function ch_effect_temp:vfx/ginga/explotion/play
execute as @n[tag=aj.chain_blast.root] at @s positioned ~-0.5 ~0.75 ~-0.5 run function ch_effect_temp:vfx/ginga/explotion/play
execute as @n[tag=aj.chain_blast.root] at @s positioned ~ ~1.25 ~ run function ch_effect_temp:vfx/ginga/explotion/play
execute as @n[tag=aj.chain_blast.root] at @s positioned ~ ~1.25 ~ run function ch_effect_temp:vfx/ginga/big_smoke/play
execute as @n[tag=aj.chain_blast.root] at @s positioned ~-0.5 ~0.75 ~0.25 run function ch_effect_temp:vfx/ginga/big_smoke/play
execute as @n[tag=aj.chain_blast.root] at @s positioned ~ ~0.25 ~0.5 run function ch_effect_temp:vfx/ginga/big_smoke/play
execute as @n[tag=aj.chain_blast.root] at @s positioned ~-0.5 ~1.125 ~-0.5 run function ch_effect_temp:vfx/ginga/big_smoke/play
execute as @n[tag=aj.chain_blast.root] at @s positioned ~ ~1.25 ~-0.25 run function ch_effect_temp:vfx/ginga/big_smoke/play
execute as @n[tag=aj.chain_blast.root] at @s positioned ~0.5 ~0.75 ~-0.25 run function ch_effect_temp:vfx/ginga/big_smoke/play
execute as @n[tag=aj.chain_blast.root] at @s positioned ~ ~0.25 ~-0.5 run function ch_effect_temp:vfx/ginga/big_smoke/play
execute as @n[tag=aj.chain_blast.root] at @s positioned ~0.5 ~1.125 ~0.5 run function ch_effect_temp:vfx/ginga/big_smoke/play
execute as @n[tag=aj.chain_blast.root] at @s positioned ~ ~1.25 ~ run function ch_effect_temp:vfx/ginga/flash/play

execute as @n[tag=aj.chain_blast.root] at @s run playsound entity.zombie.break_wooden_door hostile @a ~ ~ ~ 1 0
execute as @n[tag=aj.chain_blast.root] at @s run playsound trip_magic:entity.ginunga.chain_blast hostile @a ~ ~ ~ 1 1

execute as @n[tag=aj.chain_blast.root] at @s as @e[distance=..3] at @s run damage @s 15 ch_trip_and_magic:entity/ginunga/chain_blast.blast at ~ ~-0.25 ~