# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_blast1) {transformation: [0f,0f,-2.2f,0.0688f,0f,1.2f,0f,0.6f,2.4f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_blast) {transformation: [-2.2f,0f,0f,0f,0f,1.2f,0f,0f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone5) {transformation: [1.9053f,-1.1f,0f,-5.382f,-0.6f,-1.0392f,0f,-3.2212f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone4) {transformation: [1.9053f,-1.1f,0f,-4.5467f,-0.6f,-1.0392f,0f,-2.432f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone3) {transformation: [1.9053f,-1.1f,0f,-3.7217f,-0.6f,-1.0392f,0f,-1.6526f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone2) {transformation: [1.9053f,-1.1f,0f,-2.8967f,-0.6f,-1.0392f,0f,-0.8732f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone1) {transformation: [1.9053f,-1.1f,0f,-2.1312f,-0.6f,-1.0392f,0f,-0.075f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone10) {transformation: [0f,0f,-2.2f,0f,-0.6f,-1.0392f,0f,-3.2212f,-2.0785f,1.2f,0f,5.8713f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone9) {transformation: [0f,0f,-2.2f,0f,-0.6f,-1.0392f,0f,-2.432f,-2.0785f,1.2f,0f,4.96f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone8) {transformation: [0f,0f,-2.2f,0f,-0.6f,-1.0392f,0f,-1.6526f,-2.0785f,1.2f,0f,4.06f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone7) {transformation: [0f,0f,-2.2f,0f,-0.6f,-1.0392f,0f,-0.8732f,-2.0785f,1.2f,0f,3.16f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone6) {transformation: [0f,0f,-2.2f,0f,-0.6f,-1.0392f,0f,-0.075f,-2.0785f,1.2f,0f,2.325f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone20) {transformation: [-1.9053f,1.1f,0f,5.382f,-0.6f,-1.0392f,0f,-3.2212f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone19) {transformation: [-1.9053f,1.1f,0f,4.5467f,-0.6f,-1.0392f,0f,-2.432f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone18) {transformation: [-1.9053f,1.1f,0f,3.7217f,-0.6f,-1.0392f,0f,-1.6526f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone17) {transformation: [-1.9053f,1.1f,0f,2.8967f,-0.6f,-1.0392f,0f,-0.8732f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone16) {transformation: [-1.9053f,1.1f,0f,2.1313f,-0.6f,-1.0392f,0f,-0.075f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone15) {transformation: [0f,0f,2.2f,0f,-0.6f,-1.0392f,0f,-3.2212f,2.0785f,-1.2f,0f,-5.8713f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone14) {transformation: [0f,0f,2.2f,0f,-0.6f,-1.0392f,0f,-2.432f,2.0785f,-1.2f,0f,-4.96f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone13) {transformation: [0f,0f,2.2f,0f,-0.6f,-1.0392f,0f,-1.6526f,2.0785f,-1.2f,0f,-4.06f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone12) {transformation: [0f,0f,2.2f,0f,-0.6f,-1.0392f,0f,-0.8732f,2.0785f,-1.2f,0f,-3.16f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone11) {transformation: [0f,0f,2.2f,0f,-0.6f,-1.0392f,0f,-0.075f,2.0785f,-1.2f,0f,-2.325f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}

playsound block.chain.break hostile @a ~1.25 ~ ~ 1 1
playsound block.chain.break hostile @a ~-1.25 ~ ~ 1 1
playsound block.chain.break hostile @a ~ ~ ~1.25 1 1
playsound block.chain.break hostile @a ~ ~ ~-1.25 1 1