# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_bone5) {transformation: [-2.0251f,-0.8596f,0f,1.3986f,-0.4689f,1.1046f,0f,-0.1861f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone4) {transformation: [-2.1916f,-0.1917f,0f,1.5127f,-0.1046f,1.1954f,0f,-0.8974f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone3) {transformation: [-2.1946f,0.1535f,0f,1.5127f,0.0837f,1.1971f,0f,-0.8974f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone2) {transformation: [-2.1946f,0.1535f,0f,1.5127f,0.0837f,1.1971f,0f,-0.8974f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone1) {transformation: [-2.1946f,0.1535f,0f,1.5813f,0.0837f,1.1971f,0f,-0.9f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone10) {transformation: [0f,0f,-2.2f,0f,-0.4689f,1.1046f,0f,-0.1861f,2.2092f,0.9378f,0f,-1.5257f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone9) {transformation: [0f,0f,-2.2f,0f,-0.1046f,1.1954f,0f,-0.8974f,2.3909f,0.2092f,0f,-1.6502f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone8) {transformation: [0f,0f,-2.2f,0f,0.0837f,1.1971f,0f,-0.8974f,2.3942f,-0.1674f,0f,-1.6502f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone7) {transformation: [0f,0f,-2.2f,0f,0.0837f,1.1971f,0f,-0.8974f,2.3942f,-0.1674f,0f,-1.6502f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone6) {transformation: [0f,0f,-2.2f,0f,0.0837f,1.1971f,0f,-0.9f,2.3942f,-0.1674f,0f,-1.725f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone20) {transformation: [2.0251f,0.8596f,0f,-1.3986f,-0.4689f,1.1046f,0f,-0.1861f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone19) {transformation: [2.1916f,0.1917f,0f,-1.5127f,-0.1046f,1.1954f,0f,-0.8974f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone18) {transformation: [2.1946f,-0.1535f,0f,-1.5127f,0.0837f,1.1971f,0f,-0.8974f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone17) {transformation: [2.1946f,-0.1535f,0f,-1.5127f,0.0837f,1.1971f,0f,-0.8974f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone16) {transformation: [2.1946f,-0.1535f,0f,-1.5812f,0.0837f,1.1971f,0f,-0.9f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone15) {transformation: [0f,0f,2.2f,0f,-0.4689f,1.1046f,0f,-0.1861f,-2.2092f,-0.9378f,0f,1.5257f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone14) {transformation: [0f,0f,2.2f,0f,-0.1046f,1.1954f,0f,-0.8974f,-2.3909f,-0.2092f,0f,1.6502f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone13) {transformation: [0f,0f,2.2f,0f,0.0837f,1.1971f,0f,-0.8974f,-2.3942f,0.1674f,0f,1.6502f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone12) {transformation: [0f,0f,2.2f,0f,0.0837f,1.1971f,0f,-0.8974f,-2.3942f,0.1674f,0f,1.6502f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone11) {transformation: [0f,0f,2.2f,0f,0.0837f,1.1971f,0f,-0.9f,-2.3942f,0.1674f,0f,1.725f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute as @n[tag=aj.chain_blast.root] at @s run particle dust{color:[0.239,0.047,0.569],scale:1.5} ~1.25 ~ ~ 0.0 0.0 0.0 0.0125 4
execute as @n[tag=aj.chain_blast.root] at @s run particle dust{color:[0.239,0.047,0.569],scale:1.5} ~-1.25 ~ ~ 0.0 0.0 0.0 0.0125 4
execute as @n[tag=aj.chain_blast.root] at @s run particle dust{color:[0.239,0.047,0.569],scale:1.5} ~ ~ ~1.25 0.0 0.0 0.0 0.0125 4
execute as @n[tag=aj.chain_blast.root] at @s run particle dust{color:[0.239,0.047,0.569],scale:1.5} ~ ~ ~-1.25 0.0 0.0 0.0 0.0125 4

playsound block.chain.break hostile @a ~1.25 ~ ~ 1 1
playsound block.chain.break hostile @a ~-1.25 ~ ~ 1 1
playsound block.chain.break hostile @a ~ ~ ~1.25 1 1
playsound block.chain.break hostile @a ~ ~ ~-1.25 1 1

execute as @n[tag=aj.chain_blast.root] at @s as @e[distance=..3] at @s run damage @s 0.5 ls_trip_and_magic:entity/ginunga/chain_blast
execute as @n[tag=aj.chain_blast.root] at @s run effect give @e[distance=..2] slowness 1 2 true