# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_bone5) {transformation: [-1.3845f,-1.7097f,0f,1.132f,-0.9326f,0.7552f,0f,0.5214f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone4) {transformation: [-2.125f,-0.5694f,0f,1.5644f,-0.3106f,1.1591f,0f,-0.3588f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone3) {transformation: [-2.197f,0.1151f,0f,1.5126f,0.0628f,1.1984f,0f,-0.898f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone2) {transformation: [-2.197f,0.1151f,0f,1.5126f,0.0628f,1.1984f,0f,-0.898f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone1) {transformation: [-2.197f,0.1151f,0f,1.5813f,0.0628f,1.1984f,0f,-0.9f,0f,0f,-2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone10) {transformation: [0f,0f,-2.2f,0f,-0.9326f,0.7552f,0f,0.5214f,1.5104f,1.8652f,0f,-1.2349f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone9) {transformation: [0f,0f,-2.2f,0f,-0.3106f,1.1591f,0f,-0.3588f,2.3182f,0.6212f,0f,-1.7066f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone8) {transformation: [0f,0f,-2.2f,0f,0.0628f,1.1984f,0f,-0.898f,2.3967f,-0.1256f,0f,-1.6501f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone7) {transformation: [0f,0f,-2.2f,0f,0.0628f,1.1984f,0f,-0.898f,2.3967f,-0.1256f,0f,-1.6501f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone6) {transformation: [0f,0f,-2.2f,0f,0.0628f,1.1984f,0f,-0.9f,2.3967f,-0.1256f,0f,-1.725f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone20) {transformation: [1.3845f,1.7097f,0f,-1.132f,-0.9326f,0.7552f,0f,0.5214f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone19) {transformation: [2.125f,0.5694f,0f,-1.5644f,-0.3106f,1.1591f,0f,-0.3588f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone18) {transformation: [2.197f,-0.1151f,0f,-1.5126f,0.0628f,1.1984f,0f,-0.898f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone17) {transformation: [2.197f,-0.1151f,0f,-1.5126f,0.0628f,1.1984f,0f,-0.898f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone16) {transformation: [2.197f,-0.1151f,0f,-1.5812f,0.0628f,1.1984f,0f,-0.9f,0f,0f,2.4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone15) {transformation: [0f,0f,2.2f,0f,-0.9326f,0.7552f,0f,0.5214f,-1.5104f,-1.8652f,0f,1.2349f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone14) {transformation: [0f,0f,2.2f,0f,-0.3106f,1.1591f,0f,-0.3588f,-2.3182f,-0.6212f,0f,1.7066f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone13) {transformation: [0f,0f,2.2f,0f,0.0628f,1.1984f,0f,-0.898f,-2.3967f,0.1256f,0f,1.6501f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone12) {transformation: [0f,0f,2.2f,0f,0.0628f,1.1984f,0f,-0.898f,-2.3967f,0.1256f,0f,1.6501f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone11) {transformation: [0f,0f,2.2f,0f,0.0628f,1.1984f,0f,-0.9f,-2.3967f,0.1256f,0f,1.725f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}

playsound block.chain.break hostile @a ~1.25 ~ ~ 1 1
playsound block.chain.break hostile @a ~-1.25 ~ ~ 1 1
playsound block.chain.break hostile @a ~ ~ ~1.25 1 1
playsound block.chain.break hostile @a ~ ~ ~-1.25 1 1

execute as @n[tag=aj.chain_blast.root] at @s as @e[distance=..3] at @s run damage @s 0.25 ch_trip_and_magic:entity/ginunga/chain_blast
execute as @n[tag=aj.chain_blast.root] at @s run effect give @e[distance=..2] slowness 1 2 true