# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.chain_blast.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'chain_blast', 'function_path': 'animated_java:chain_blast/animations/animation.model.summon/play'}
tag @s add aj.chain_blast.animation.animation.model.summon.playing
scoreboard players set @s aj.animation.model.summon.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:chain_blast/animations/animation.model.summon/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only