# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.ginunga.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'ginunga', 'function_path': 'animated_java:ginunga/animations/animation.model.set_rand_mine/stop'}
tag @s remove aj.ginunga.animation.animation.model.set_rand_mine.playing
scoreboard players set @s aj.animation.model.set_rand_mine.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:ginunga/animations/animation.model.set_rand_mine/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only