# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_shockwave) {transformation: [3349.337f,0f,-210.2911f,0f,0f,3355.9322f,0f,73.5132f,210.2911f,0f,3349.337f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_2) {transformation: [-2.4793f,0f,-2.9547f,-1.6875f,-2.0893f,2.7274f,1.7531f,4.7075f,2.0893f,2.7274f,-1.7531f,-2.8929f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_6) {transformation: [1.1018f,-2.9683f,-2.203f,1.6875f,-3.6114f,-0.3741f,-1.3021f,4.7075f,0.7883f,2.4345f,-2.886f,1.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_7) {transformation: [3.7434f,0.2945f,0.8818f,-2.4107f,-0.5581f,-2.2138f,3.1089f,4.7075f,0.7435f,-3.1448f,-2.1059f,1.9286f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_8) {transformation: [-0.1682f,1.318f,-3.6211f,2.4107f,-2.7248f,2.5222f,1.0446f,4.7075f,2.7248f,2.6036f,0.821f,-1.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_9) {transformation: [-2.0309f,-2.3469f,2.2902f,0f,-0.1471f,-2.6259f,-2.8214f,4.7075f,3.2758f,-1.5729f,1.2932f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_10) {transformation: [-0.8264f,0f,-0.9849f,0.4018f,-0.6964f,0.9091f,0.5844f,7.9314f,0.6964f,0.9091f,-0.5844f,-0.5625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_11) {transformation: [0.3673f,-0.9894f,-0.7343f,-0.5625f,-1.2038f,-0.1247f,-0.434f,7.9314f,0.2628f,0.8115f,-0.962f,-0.9643f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_12) {transformation: [1.2478f,0.0982f,0.2939f,0.4018f,-0.186f,-0.7379f,1.0363f,7.9314f,0.2478f,-1.0483f,-0.702f,0.0804f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_13) {transformation: [-0.0561f,0.4393f,-1.207f,-0.5625f,-0.9083f,0.8407f,0.3482f,7.9314f,0.9083f,0.8679f,0.2737f,0.0804f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_14) {transformation: [-0.677f,-0.7823f,0.7634f,0f,-0.049f,-0.8753f,-0.9405f,7.9314f,1.0919f,-0.5243f,0.4311f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_15) {transformation: [0f,0f,0f,0f,0f,0f,0f,8.7666f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_16) {transformation: [0f,0f,0f,0f,0f,0f,0f,8.7666f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_17) {transformation: [0f,0f,0f,0f,0f,0f,0f,8.7666f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_18) {transformation: [0f,0f,0f,0f,0f,0f,0f,8.7666f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_19) {transformation: [0f,0f,0f,0f,0f,0f,0f,8.7666f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}