# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_shockwave) {transformation: [1579.3983f,0f,-2980.2399f,0f,0f,3372.8814f,0f,74.2229f,2980.2399f,0f,1579.3983f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_2) {transformation: [-2.4105f,0f,-2.8727f,-1.6406f,-2.0313f,2.6517f,1.7044f,4.6772f,2.0313f,2.6517f,-1.7044f,-2.8125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_6) {transformation: [1.0712f,-2.8858f,-2.1418f,1.6406f,-3.5111f,-0.3637f,-1.2659f,4.6772f,0.7664f,2.3669f,-2.8058f,1.6406f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_7) {transformation: [3.6395f,0.2864f,0.8573f,-2.3437f,-0.5426f,-2.1523f,3.0225f,4.6772f,0.7228f,-3.0575f,-2.0474f,1.875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_8) {transformation: [-0.1636f,1.2814f,-3.5205f,2.3437f,-2.6491f,2.4522f,1.0156f,4.6772f,2.6491f,2.5313f,0.7982f,-1.6406f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_9) {transformation: [-1.9745f,-2.2817f,2.2266f,0f,-0.143f,-2.553f,-2.743f,4.6772f,3.1849f,-1.5292f,1.2572f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_10) {transformation: [-0.7499f,0f,-0.8937f,0.3646f,-0.632f,0.825f,0.5303f,7.7837f,0.632f,0.825f,-0.5303f,-0.5104f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_11) {transformation: [0.3333f,-0.8978f,-0.6663f,-0.5104f,-1.0923f,-0.1132f,-0.3938f,7.7837f,0.2384f,0.7364f,-0.8729f,-0.875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_12) {transformation: [1.1323f,0.0891f,0.2667f,0.3646f,-0.1688f,-0.6696f,0.9403f,7.7837f,0.2249f,-0.9512f,-0.637f,0.0729f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_13) {transformation: [-0.0509f,0.3986f,-1.0953f,-0.5104f,-0.8242f,0.7629f,0.316f,7.7837f,0.8242f,0.7875f,0.2483f,0.0729f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_14) {transformation: [-0.6143f,-0.7099f,0.6927f,0f,-0.0445f,-0.7943f,-0.8534f,7.7837f,0.9908f,-0.4758f,0.3911f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_15) {transformation: [0f,0f,0f,0f,0f,0f,0f,8.5483f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_16) {transformation: [0f,0f,0f,0f,0f,0f,0f,8.5483f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_17) {transformation: [0f,0f,0f,0f,0f,0f,0f,8.5483f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_18) {transformation: [0f,0f,0f,0f,0f,0f,0f,8.5483f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_19) {transformation: [0f,0f,0f,0f,0f,0f,0f,8.5483f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}