# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_shockwave) {transformation: [2805.4993f,0f,-1902.6625f,0f,0f,3389.8305f,0f,74.9269f,1902.6625f,0f,2805.4993f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_2) {transformation: [-2.3416f,0f,-2.7906f,-1.5937f,-1.9732f,2.5759f,1.6557f,4.6469f,1.9732f,2.5759f,-1.6557f,-2.7321f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_6) {transformation: [1.0406f,-2.8034f,-2.0806f,1.5938f,-3.4108f,-0.3533f,-1.2298f,4.6469f,0.7445f,2.2993f,-2.7257f,1.5938f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_7) {transformation: [3.5355f,0.2782f,0.8328f,-2.2768f,-0.5271f,-2.0908f,2.9362f,4.6469f,0.7022f,-2.9701f,-1.9889f,1.8214f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_8) {transformation: [-0.1589f,1.2447f,-3.4199f,2.2768f,-2.5734f,2.3821f,0.9866f,4.6469f,2.5734f,2.459f,0.7754f,-1.5938f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_9) {transformation: [-1.9181f,-2.2165f,2.1629f,0f,-0.1389f,-2.48f,-2.6647f,4.6469f,3.0939f,-1.4855f,1.2213f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_10) {transformation: [-0.6765f,0f,-0.8062f,0.3289f,-0.57f,0.7441f,0.4783f,7.6375f,0.57f,0.7441f,-0.4783f,-0.4604f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_11) {transformation: [0.3006f,-0.8099f,-0.6011f,-0.4604f,-0.9853f,-0.1021f,-0.3553f,7.6375f,0.2151f,0.6642f,-0.7874f,-0.7893f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_12) {transformation: [1.0214f,0.0804f,0.2406f,0.3289f,-0.1523f,-0.604f,0.8482f,7.6375f,0.2029f,-0.858f,-0.5746f,0.0658f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_13) {transformation: [-0.0459f,0.3596f,-0.988f,-0.4604f,-0.7434f,0.6882f,0.285f,7.6375f,0.7434f,0.7104f,0.224f,0.0658f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_14) {transformation: [-0.5541f,-0.6403f,0.6248f,0f,-0.0401f,-0.7165f,-0.7698f,7.6375f,0.8938f,-0.4292f,0.3528f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_15) {transformation: [0f,0f,0f,0f,0f,0f,0f,8.3334f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_16) {transformation: [0f,0f,0f,0f,0f,0f,0f,8.3334f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_17) {transformation: [0f,0f,0f,0f,0f,0f,0f,8.3334f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_18) {transformation: [0f,0f,0f,0f,0f,0f,0f,8.3334f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_19) {transformation: [0f,0f,0f,0f,0f,0f,0f,8.3334f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}