# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_shockwave) {transformation: [840.311f,0f,3301.5186f,0f,0f,3406.7797f,0f,75.6249f,-3301.5186f,0f,840.311f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_2) {transformation: [-2.2727f,0f,-2.7085f,-1.5469f,-1.9152f,2.5001f,1.6071f,4.6166f,1.9152f,2.5001f,-1.6071f,-2.6518f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_6) {transformation: [1.01f,-2.7209f,-2.0194f,1.5469f,-3.3104f,-0.343f,-1.1936f,4.6166f,0.7226f,2.2317f,-2.6455f,1.5469f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_7) {transformation: [3.4315f,0.27f,0.8083f,-2.2098f,-0.5116f,-2.0293f,2.8498f,4.6166f,0.6815f,-2.8827f,-1.9304f,1.7679f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_8) {transformation: [-0.1542f,1.2081f,-3.3193f,2.2098f,-2.4977f,2.3121f,0.9576f,4.6166f,2.4977f,2.3867f,0.7526f,-1.5469f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_9) {transformation: [-1.8617f,-2.1513f,2.0993f,0f,-0.1348f,-2.4071f,-2.5863f,4.6166f,3.0029f,-1.4419f,1.1854f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_10) {transformation: [-0.6061f,0f,-0.7223f,0.2946f,-0.5107f,0.6667f,0.4285f,7.493f,0.5107f,0.6667f,-0.4285f,-0.4125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_11) {transformation: [0.2693f,-0.7256f,-0.5385f,-0.4125f,-0.8828f,-0.0915f,-0.3183f,7.493f,0.1927f,0.5951f,-0.7055f,-0.7071f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_12) {transformation: [0.9151f,0.072f,0.2155f,0.2946f,-0.1364f,-0.5412f,0.7599f,7.493f,0.1817f,-0.7687f,-0.5148f,0.0589f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_13) {transformation: [-0.0411f,0.3222f,-0.8852f,-0.4125f,-0.6661f,0.6165f,0.2554f,7.493f,0.6661f,0.6364f,0.2007f,0.0589f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_14) {transformation: [-0.4965f,-0.5737f,0.5598f,0f,-0.036f,-0.6419f,-0.6897f,7.493f,0.8008f,-0.3845f,0.3161f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_15) {transformation: [0f,0f,0f,0f,0f,0f,0f,8.1218f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_16) {transformation: [0f,0f,0f,0f,0f,0f,0f,8.1218f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_17) {transformation: [0f,0f,0f,0f,0f,0f,0f,8.1218f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_18) {transformation: [0f,0f,0f,0f,0f,0f,0f,8.1218f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_19) {transformation: [0f,0f,0f,0f,0f,0f,0f,8.1218f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}