# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_shockwave) {transformation: [-408.4712f,0f,-3399.275f,0f,0f,3423.7288f,0f,76.3168f,3399.275f,0f,-408.4712f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_2) {transformation: [-2.2038f,0f,-2.6264f,-1.5f,-1.8572f,2.4244f,1.5584f,4.5862f,1.8572f,2.4244f,-1.5584f,-2.5714f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_6) {transformation: [0.9794f,-2.6384f,-1.9582f,1.5f,-3.2101f,-0.3326f,-1.1574f,4.5862f,0.7007f,2.164f,-2.5653f,1.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_7) {transformation: [3.3275f,0.2618f,0.7838f,-2.1429f,-0.4961f,-1.9678f,2.7634f,4.5862f,0.6609f,-2.7954f,-1.8719f,1.7143f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_8) {transformation: [-0.1496f,1.1715f,-3.2187f,2.1429f,-2.4221f,2.242f,0.9286f,4.5862f,2.4221f,2.3143f,0.7298f,-1.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_9) {transformation: [-1.8053f,-2.0861f,2.0357f,0f,-0.1307f,-2.3342f,-2.5079f,4.5862f,2.9119f,-1.3982f,1.1495f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_10) {transformation: [-0.5387f,0f,-0.642f,0.2619f,-0.454f,0.5926f,0.3809f,7.3501f,0.454f,0.5926f,-0.3809f,-0.3667f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_11) {transformation: [0.2394f,-0.645f,-0.4787f,-0.3667f,-0.7847f,-0.0813f,-0.2829f,7.3501f,0.1713f,0.529f,-0.6271f,-0.6286f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_12) {transformation: [0.8134f,0.064f,0.1916f,0.2619f,-0.1213f,-0.481f,0.6755f,7.3501f,0.1615f,-0.6833f,-0.4576f,0.0524f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_13) {transformation: [-0.0366f,0.2864f,-0.7868f,-0.3667f,-0.5921f,0.548f,0.227f,7.3501f,0.5921f,0.5657f,0.1784f,0.0524f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_14) {transformation: [-0.4413f,-0.5099f,0.4976f,0f,-0.032f,-0.5706f,-0.613f,7.3501f,0.7118f,-0.3418f,0.281f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_15) {transformation: [0f,0f,0f,0f,0f,0f,0f,7.9139f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_16) {transformation: [0f,0f,0f,0f,0f,0f,0f,7.9139f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_17) {transformation: [0f,0f,0f,0f,0f,0f,0f,7.9139f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_18) {transformation: [0f,0f,0f,0f,0f,0f,0f,7.9139f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_19) {transformation: [0f,0f,0f,0f,0f,0f,0f,7.9139f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}