# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_shockwave) {transformation: [-3305.5658f,0f,954.7247f,0f,0f,3440.678f,0f,77.0022f,-954.7247f,0f,-3305.5658f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_2) {transformation: [-2.135f,0f,-2.5444f,-1.4531f,-1.7991f,2.3486f,1.5097f,4.5559f,1.7991f,2.3486f,-1.5097f,-2.4911f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_6) {transformation: [0.9488f,-2.556f,-1.897f,1.4531f,-3.1098f,-0.3222f,-1.1212f,4.5559f,0.6788f,2.0964f,-2.4852f,1.4531f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_7) {transformation: [3.2235f,0.2536f,0.7593f,-2.0759f,-0.4806f,-1.9063f,2.6771f,4.5559f,0.6402f,-2.708f,-1.8134f,1.6607f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_8) {transformation: [-0.1449f,1.1349f,-3.1182f,2.0759f,-2.3464f,2.1719f,0.8995f,4.5559f,2.3464f,2.242f,0.707f,-1.4531f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_9) {transformation: [-1.7489f,-2.0209f,1.9721f,0f,-0.1267f,-2.2612f,-2.4296f,4.5559f,2.8209f,-1.3545f,1.1136f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_10) {transformation: [-0.4744f,0f,-0.5654f,0.2307f,-0.3998f,0.5219f,0.3355f,7.2087f,0.3998f,0.5219f,-0.3355f,-0.3229f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_11) {transformation: [0.2108f,-0.568f,-0.4216f,-0.3229f,-0.6911f,-0.0716f,-0.2492f,7.2087f,0.1509f,0.4659f,-0.5523f,-0.5536f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_12) {transformation: [0.7163f,0.0564f,0.1687f,0.2307f,-0.1068f,-0.4236f,0.5949f,7.2087f,0.1423f,-0.6018f,-0.403f,0.0461f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_13) {transformation: [-0.0322f,0.2522f,-0.6929f,-0.3229f,-0.5214f,0.4827f,0.1999f,7.2087f,0.5214f,0.4982f,0.1571f,0.0461f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_14) {transformation: [-0.3886f,-0.4491f,0.4382f,0f,-0.0281f,-0.5025f,-0.5399f,7.2087f,0.6269f,-0.301f,0.2475f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_15) {transformation: [0f,0f,0f,0f,0f,0f,0f,7.7095f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_16) {transformation: [0f,0f,0f,0f,0f,0f,0f,7.7095f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_17) {transformation: [0f,0f,0f,0f,0f,0f,0f,7.7095f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_18) {transformation: [0f,0f,0f,0f,0f,0f,0f,7.7095f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_19) {transformation: [0f,0f,0f,0f,0f,0f,0f,7.7095f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}