# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_shockwave) {transformation: [-2393.9327f,0f,2494.849f,0f,0f,3457.6271f,0f,77.6809f,-2494.849f,0f,-2393.9327f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_2) {transformation: [-2.0661f,0f,-2.4623f,-1.4062f,-1.7411f,2.2728f,1.461f,4.5256f,1.7411f,2.2728f,-1.461f,-2.4107f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_6) {transformation: [0.9182f,-2.4735f,-1.8358f,1.4062f,-3.0095f,-0.3118f,-1.0851f,4.5256f,0.657f,2.0288f,-2.405f,1.4062f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_7) {transformation: [3.1195f,0.2454f,0.7348f,-2.0089f,-0.4651f,-1.8448f,2.5907f,4.5256f,0.6196f,-2.6207f,-1.7549f,1.6071f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_8) {transformation: [-0.1402f,1.0983f,-3.0176f,2.0089f,-2.2707f,2.1019f,0.8705f,4.5256f,2.2707f,2.1697f,0.6842f,-1.4062f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_9) {transformation: [-1.6925f,-1.9558f,1.9085f,0f,-0.1226f,-2.1883f,-2.3512f,4.5256f,2.7299f,-1.3108f,1.0776f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_10) {transformation: [-0.4132f,0f,-0.4925f,0.2009f,-0.3482f,0.4546f,0.2922f,7.0689f,0.3482f,0.4546f,-0.2922f,-0.2812f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_11) {transformation: [0.1836f,-0.4947f,-0.3672f,-0.2812f,-0.6019f,-0.0624f,-0.217f,7.0689f,0.1314f,0.4058f,-0.481f,-0.4821f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_12) {transformation: [0.6239f,0.0491f,0.147f,0.2009f,-0.093f,-0.369f,0.5181f,7.0689f,0.1239f,-0.5241f,-0.351f,0.0402f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_13) {transformation: [-0.028f,0.2197f,-0.6035f,-0.2812f,-0.4541f,0.4204f,0.1741f,7.0689f,0.4541f,0.4339f,0.1368f,0.0402f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_14) {transformation: [-0.3385f,-0.3912f,0.3817f,0f,-0.0245f,-0.4377f,-0.4702f,7.0689f,0.546f,-0.2622f,0.2155f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_15) {transformation: [0f,0f,0f,0f,0f,0f,0f,7.5088f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_16) {transformation: [0f,0f,0f,0f,0f,0f,0f,7.5088f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_17) {transformation: [0f,0f,0f,0f,0f,0f,0f,7.5088f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_18) {transformation: [0f,0f,0f,0f,0f,0f,0f,7.5088f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_19) {transformation: [0f,0f,0f,0f,0f,0f,0f,7.5088f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}