# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_shockwave) {transformation: [-3409.8194f,0f,667.6917f,0f,0f,3474.5763f,0f,78.3528f,-667.6917f,0f,-3409.8194f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_2) {transformation: [-1.9972f,0f,-2.3802f,-1.3594f,-1.6831f,2.1971f,1.4123f,4.4953f,1.6831f,2.1971f,-1.4123f,-2.3304f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_6) {transformation: [0.8876f,-2.3911f,-1.7746f,1.3594f,-2.9092f,-0.3014f,-1.0489f,4.4953f,0.6351f,1.9612f,-2.3248f,1.3594f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_7) {transformation: [3.0155f,0.2373f,0.7103f,-1.942f,-0.4496f,-1.7833f,2.5044f,4.4953f,0.5989f,-2.5333f,-1.6964f,1.5536f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_8) {transformation: [-0.1355f,1.0617f,-2.917f,1.942f,-2.195f,2.0318f,0.8415f,4.4953f,2.195f,2.0974f,0.6614f,-1.3594f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_9) {transformation: [-1.636f,-1.8906f,1.8449f,0f,-0.1185f,-2.1153f,-2.2728f,4.4953f,2.6389f,-1.2671f,1.0417f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_10) {transformation: [-0.3551f,0f,-0.4231f,0.1726f,-0.2992f,0.3906f,0.2511f,6.9307f,0.2992f,0.3906f,-0.2511f,-0.2417f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_11) {transformation: [0.1578f,-0.4251f,-0.3155f,-0.2417f,-0.5172f,-0.0536f,-0.1865f,6.9307f,0.1129f,0.3487f,-0.4133f,-0.4143f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_12) {transformation: [0.5361f,0.0422f,0.1263f,0.1726f,-0.0799f,-0.317f,0.4452f,6.9307f,0.1065f,-0.4504f,-0.3016f,0.0345f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_13) {transformation: [-0.0241f,0.1887f,-0.5186f,-0.2417f,-0.3902f,0.3612f,0.1496f,6.9307f,0.3902f,0.3729f,0.1176f,0.0345f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_14) {transformation: [-0.2909f,-0.3361f,0.328f,0f,-0.0211f,-0.3761f,-0.4041f,6.9307f,0.4691f,-0.2253f,0.1852f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_15) {transformation: [0f,0f,0f,0f,0f,0f,0f,7.3119f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_16) {transformation: [0f,0f,0f,0f,0f,0f,0f,7.3119f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_17) {transformation: [0f,0f,0f,0f,0f,0f,0f,7.3119f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_18) {transformation: [0f,0f,0f,0f,0f,0f,0f,7.3119f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_19) {transformation: [0f,0f,0f,0f,0f,0f,0f,7.3119f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}