# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_shockwave) {transformation: [-285.4442f,0f,-3479.8378f,0f,0f,3491.5254f,0f,79.0175f,3479.8378f,0f,-285.4442f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_2) {transformation: [-1.9284f,0f,-2.2981f,-1.3125f,-1.625f,2.1213f,1.3636f,4.465f,1.625f,2.1213f,-1.3636f,-2.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_6) {transformation: [0.8569f,-2.3086f,-1.7134f,1.3125f,-2.8089f,-0.291f,-1.0127f,4.465f,0.6132f,1.8935f,-2.2447f,1.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_7) {transformation: [2.9116f,0.2291f,0.6858f,-1.875f,-0.4341f,-1.7219f,2.418f,4.465f,0.5783f,-2.446f,-1.6379f,1.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_8) {transformation: [-0.1309f,1.0251f,-2.8164f,1.875f,-2.1193f,1.9617f,0.8125f,4.465f,2.1193f,2.025f,0.6386f,-1.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_9) {transformation: [-1.5796f,-1.8254f,1.7812f,0f,-0.1144f,-2.0424f,-2.1944f,4.465f,2.5479f,-1.2234f,1.0058f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_10) {transformation: [-0.3f,0f,-0.3575f,0.1458f,-0.2528f,0.33f,0.2121f,6.7942f,0.2528f,0.33f,-0.2121f,-0.2042f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_11) {transformation: [0.1333f,-0.3591f,-0.2665f,-0.2042f,-0.4369f,-0.0453f,-0.1575f,6.7942f,0.0954f,0.2946f,-0.3492f,-0.35f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_12) {transformation: [0.4529f,0.0356f,0.1067f,0.1458f,-0.0675f,-0.2678f,0.3761f,6.7942f,0.09f,-0.3805f,-0.2548f,0.0292f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_13) {transformation: [-0.0204f,0.1595f,-0.4381f,-0.2042f,-0.3297f,0.3052f,0.1264f,6.7942f,0.3297f,0.315f,0.0993f,0.0292f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_14) {transformation: [-0.2457f,-0.2839f,0.2771f,0f,-0.0178f,-0.3177f,-0.3414f,6.7942f,0.3963f,-0.1903f,0.1565f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_15) {transformation: [0f,0f,0f,0f,0f,0f,0f,7.1189f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_16) {transformation: [0f,0f,0f,0f,0f,0f,0f,7.1189f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_17) {transformation: [0f,0f,0f,0f,0f,0f,0f,7.1189f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_18) {transformation: [0f,0f,0f,0f,0f,0f,0f,7.1189f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_19) {transformation: [0f,0f,0f,0f,0f,0f,0f,7.1189f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}