# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_shockwave) {transformation: [1795.6011f,0f,3014.1683f,0f,0f,3508.4746f,0f,79.6748f,-3014.1683f,0f,1795.6011f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_2) {transformation: [-1.8595f,0f,-2.2161f,-1.2656f,-1.567f,2.0456f,1.3149f,4.4347f,1.567f,2.0456f,-1.3149f,-2.1696f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_6) {transformation: [0.8263f,-2.2262f,-1.6522f,1.2656f,-2.7085f,-0.2806f,-0.9766f,4.4347f,0.5913f,1.8259f,-2.1645f,1.2656f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_7) {transformation: [2.8076f,0.2209f,0.6613f,-1.808f,-0.4186f,-1.6604f,2.3317f,4.4347f,0.5576f,-2.3586f,-1.5794f,1.4464f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_8) {transformation: [-0.1262f,0.9885f,-2.7158f,1.808f,-2.0436f,1.8917f,0.7835f,4.4347f,2.0436f,1.9527f,0.6158f,-1.2656f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_9) {transformation: [-1.5232f,-1.7602f,1.7176f,0f,-0.1103f,-1.9694f,-2.1161f,4.4347f,2.4569f,-1.1797f,0.9699f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_10) {transformation: [-0.2479f,0f,-0.2955f,0.1205f,-0.2089f,0.2727f,0.1753f,6.6592f,0.2089f,0.2727f,-0.1753f,-0.1688f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_11) {transformation: [0.1102f,-0.2968f,-0.2203f,-0.1688f,-0.3611f,-0.0374f,-0.1302f,6.6592f,0.0788f,0.2435f,-0.2886f,-0.2893f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_12) {transformation: [0.3743f,0.0295f,0.0882f,0.1205f,-0.0558f,-0.2214f,0.3109f,6.6592f,0.0743f,-0.3145f,-0.2106f,0.0241f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_13) {transformation: [-0.0168f,0.1318f,-0.3621f,-0.1688f,-0.2725f,0.2522f,0.1045f,6.6592f,0.2725f,0.2604f,0.0821f,0.0241f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_14) {transformation: [-0.2031f,-0.2347f,0.229f,0f,-0.0147f,-0.2626f,-0.2821f,6.6592f,0.3276f,-0.1573f,0.1293f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_15) {transformation: [0f,0f,0f,0f,0f,0f,0f,6.9298f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_16) {transformation: [0f,0f,0f,0f,0f,0f,0f,6.9298f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_17) {transformation: [0f,0f,0f,0f,0f,0f,0f,6.9298f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_18) {transformation: [0f,0f,0f,0f,0f,0f,0f,6.9298f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_19) {transformation: [0f,0f,0f,0f,0f,0f,0f,6.9298f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}