# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_shockwave) {transformation: [-185.1619f,0f,-3520.5578f,0f,0f,3525.4237f,0f,80.3244f,3520.5578f,0f,-185.1619f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_2) {transformation: [-1.7906f,0f,-2.134f,-1.2188f,-1.509f,1.9698f,1.2662f,4.4044f,1.509f,1.9698f,-1.2662f,-2.0893f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_6) {transformation: [0.7957f,-2.1437f,-1.591f,1.2188f,-2.6082f,-0.2702f,-0.9404f,4.4044f,0.5694f,1.7583f,-2.0843f,1.2188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_7) {transformation: [2.7036f,0.2127f,0.6368f,-1.7411f,-0.4031f,-1.5989f,2.2453f,4.4044f,0.537f,-2.2713f,-1.5209f,1.3929f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_8) {transformation: [-0.1215f,0.9519f,-2.6152f,1.7411f,-1.9679f,1.8216f,0.7544f,4.4044f,1.9679f,1.8804f,0.593f,-1.2188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_9) {transformation: [-1.4668f,-1.695f,1.654f,0f,-0.1062f,-1.8965f,-2.0377f,4.4044f,2.3659f,-1.136f,0.9339f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_10) {transformation: [-0.199f,0f,-0.2371f,0.0967f,-0.1677f,0.2189f,0.1407f,6.5258f,0.1677f,0.2189f,-0.1407f,-0.1354f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_11) {transformation: [0.0884f,-0.2382f,-0.1768f,-0.1354f,-0.2898f,-0.03f,-0.1045f,6.5258f,0.0633f,0.1954f,-0.2316f,-0.2321f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_12) {transformation: [0.3004f,0.0236f,0.0708f,0.0967f,-0.0448f,-0.1777f,0.2495f,6.5258f,0.0597f,-0.2524f,-0.169f,0.0193f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_13) {transformation: [-0.0135f,0.1058f,-0.2906f,-0.1354f,-0.2187f,0.2024f,0.0838f,6.5258f,0.2187f,0.2089f,0.0659f,0.0193f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_14) {transformation: [-0.163f,-0.1883f,0.1838f,0f,-0.0118f,-0.2107f,-0.2264f,6.5258f,0.2629f,-0.1262f,0.1038f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_15) {transformation: [0f,0f,0f,0f,0f,0f,0f,6.7447f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_16) {transformation: [0f,0f,0f,0f,0f,0f,0f,6.7447f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_17) {transformation: [0f,0f,0f,0f,0f,0f,0f,6.7447f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_18) {transformation: [0f,0f,0f,0f,0f,0f,0f,6.7447f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_19) {transformation: [0f,0f,0f,0f,0f,0f,0f,6.7447f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}