# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_shockwave) {transformation: [-3423.2231f,0f,911.0155f,0f,0f,3542.3729f,0f,80.9662f,-911.0155f,0f,-3423.2231f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_2) {transformation: [-1.7218f,0f,-2.0519f,-1.1719f,-1.4509f,1.894f,1.2175f,4.3741f,1.4509f,1.894f,-1.2175f,-2.0089f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_6) {transformation: [0.7651f,-2.0613f,-1.5298f,1.1719f,-2.5079f,-0.2598f,-0.9042f,4.3741f,0.5475f,1.6907f,-2.0042f,1.1719f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_7) {transformation: [2.5996f,0.2045f,0.6123f,-1.6741f,-0.3876f,-1.5374f,2.1589f,4.3741f,0.5163f,-2.1839f,-1.4625f,1.3393f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_8) {transformation: [-0.1168f,0.9153f,-2.5146f,1.6741f,-1.8922f,1.7516f,0.7254f,4.3741f,1.8922f,1.8081f,0.5702f,-1.1719f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_9) {transformation: [-1.4104f,-1.6298f,1.5904f,0f,-0.1021f,-1.8236f,-1.9593f,4.3741f,2.2749f,-1.0923f,0.898f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_10) {transformation: [-0.153f,0f,-0.1824f,0.0744f,-0.129f,0.1684f,0.1082f,6.394f,0.129f,0.1684f,-0.1082f,-0.1042f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_11) {transformation: [0.068f,-0.1832f,-0.136f,-0.1042f,-0.2229f,-0.0231f,-0.0804f,6.394f,0.0487f,0.1503f,-0.1781f,-0.1786f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_12) {transformation: [0.2311f,0.0182f,0.0544f,0.0744f,-0.0345f,-0.1367f,0.1919f,6.394f,0.0459f,-0.1941f,-0.13f,0.0149f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_13) {transformation: [-0.0104f,0.0814f,-0.2235f,-0.1042f,-0.1682f,0.1557f,0.0645f,6.394f,0.1682f,0.1607f,0.0507f,0.0149f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_14) {transformation: [-0.1254f,-0.1449f,0.1414f,0f,-0.0091f,-0.1621f,-0.1742f,6.394f,0.2022f,-0.0971f,0.0798f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_15) {transformation: [0f,0f,0f,0f,0f,0f,0f,6.5638f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_16) {transformation: [0f,0f,0f,0f,0f,0f,0f,6.5638f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_17) {transformation: [0f,0f,0f,0f,0f,0f,0f,6.5638f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_18) {transformation: [0f,0f,0f,0f,0f,0f,0f,6.5638f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_19) {transformation: [0f,0f,0f,0f,0f,0f,0f,6.5638f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}