# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_shockwave) {transformation: [-1224.9571f,0f,3341.8937f,0f,0f,3559.322f,0f,81.5998f,-3341.8937f,0f,-1224.9571f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_2) {transformation: [-1.6529f,0f,-1.9698f,-1.125f,-1.3929f,1.8183f,1.1688f,4.3438f,1.3929f,1.8183f,-1.1688f,-1.9286f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_6) {transformation: [0.7345f,-1.9788f,-1.4686f,1.125f,-2.4076f,-0.2494f,-0.8681f,4.3438f,0.5256f,1.623f,-1.924f,1.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_7) {transformation: [2.4956f,0.1964f,0.5878f,-1.6071f,-0.3721f,-1.4759f,2.0726f,4.3438f,0.4957f,-2.0965f,-1.404f,1.2857f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_8) {transformation: [-0.1122f,0.8786f,-2.4141f,1.6071f,-1.8165f,1.6815f,0.6964f,4.3438f,1.8165f,1.7357f,0.5474f,-1.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_9) {transformation: [-1.354f,-1.5646f,1.5268f,0f,-0.0981f,-1.7506f,-1.8809f,4.3438f,2.1839f,-1.0486f,0.8621f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_10) {transformation: [-0.1102f,0f,-0.1313f,0.0536f,-0.0929f,0.1212f,0.0779f,6.2638f,0.0929f,0.1212f,-0.0779f,-0.075f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_11) {transformation: [0.049f,-0.1319f,-0.0979f,-0.075f,-0.1605f,-0.0166f,-0.0579f,6.2638f,0.035f,0.1082f,-0.1283f,-0.1286f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_12) {transformation: [0.1664f,0.0131f,0.0392f,0.0536f,-0.0248f,-0.0984f,0.1382f,6.2638f,0.033f,-0.1398f,-0.0936f,0.0107f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_13) {transformation: [-0.0075f,0.0586f,-0.1609f,-0.075f,-0.1211f,0.1121f,0.0464f,6.2638f,0.1211f,0.1157f,0.0365f,0.0107f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_14) {transformation: [-0.0903f,-0.1043f,0.1018f,0f,-0.0065f,-0.1167f,-0.1254f,6.2638f,0.1456f,-0.0699f,0.0575f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_15) {transformation: [0f,0f,0f,0f,0f,0f,0f,6.387f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_16) {transformation: [0f,0f,0f,0f,0f,0f,0f,6.387f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_17) {transformation: [0f,0f,0f,0f,0f,0f,0f,6.387f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_18) {transformation: [0f,0f,0f,0f,0f,0f,0f,6.387f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_19) {transformation: [0f,0f,0f,0f,0f,0f,0f,6.387f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}