# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_shockwave) {transformation: [-546.9038f,0f,3534.206f,0f,0f,3576.2712f,0f,82.2251f,-3534.206f,0f,-546.9038f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_2) {transformation: [-1.584f,0f,-1.8878f,-1.0781f,-1.3348f,1.7425f,1.1201f,4.3134f,1.3348f,1.7425f,-1.1201f,-1.8482f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_6) {transformation: [0.7039f,-1.8964f,-1.4075f,1.0781f,-2.3073f,-0.239f,-0.8319f,4.3134f,0.5037f,1.5554f,-1.8438f,1.0781f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_7) {transformation: [2.3916f,0.1882f,0.5633f,-1.5402f,-0.3566f,-1.4144f,1.9862f,4.3134f,0.475f,-2.0092f,-1.3455f,1.2321f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_8) {transformation: [-0.1075f,0.842f,-2.3135f,1.5402f,-1.7409f,1.6114f,0.6674f,4.3134f,1.7409f,1.6634f,0.5246f,-1.0781f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_9) {transformation: [-1.2975f,-1.4994f,1.4632f,0f,-0.094f,-1.6777f,-1.8026f,4.3134f,2.0929f,-1.0049f,0.8262f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_10) {transformation: [-0.0704f,0f,-0.0839f,0.0342f,-0.0593f,0.0774f,0.0498f,6.1351f,0.0593f,0.0774f,-0.0498f,-0.0479f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_11) {transformation: [0.0313f,-0.0843f,-0.0626f,-0.0479f,-0.1025f,-0.0106f,-0.037f,6.1351f,0.0224f,0.0691f,-0.0819f,-0.0821f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_12) {transformation: [0.1063f,0.0084f,0.025f,0.0342f,-0.0158f,-0.0629f,0.0883f,6.1351f,0.0211f,-0.0893f,-0.0598f,0.0068f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_13) {transformation: [-0.0048f,0.0374f,-0.1028f,-0.0479f,-0.0774f,0.0716f,0.0297f,6.1351f,0.0774f,0.0739f,0.0233f,0.0068f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_14) {transformation: [-0.0577f,-0.0666f,0.065f,0f,-0.0042f,-0.0746f,-0.0801f,6.1351f,0.093f,-0.0447f,0.0367f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_15) {transformation: [0f,0f,0f,0f,0f,0f,0f,6.2145f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_16) {transformation: [0f,0f,0f,0f,0f,0f,0f,6.2145f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_17) {transformation: [0f,0f,0f,0f,0f,0f,0f,6.2145f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_18) {transformation: [0f,0f,0f,0f,0f,0f,0f,6.2145f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_19) {transformation: [0f,0f,0f,0f,0f,0f,0f,6.2145f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}