# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_shockwave) {transformation: [-2208.4896f,0f,2834.3969f,0f,0f,3593.2203f,0f,82.8417f,-2834.3969f,0f,-2208.4896f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_2) {transformation: [-1.5151f,0f,-1.8057f,-1.0313f,-1.2768f,1.6668f,1.0714f,4.2831f,1.2768f,1.6668f,-1.0714f,-1.7679f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_6) {transformation: [0.6733f,-1.8139f,-1.3463f,1.0313f,-2.207f,-0.2286f,-0.7957f,4.2831f,0.4818f,1.4878f,-1.7637f,1.0313f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_7) {transformation: [2.2877f,0.18f,0.5388f,-1.4732f,-0.3411f,-1.3529f,1.8999f,4.2831f,0.4543f,-1.9218f,-1.287f,1.1786f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_8) {transformation: [-0.1028f,0.8054f,-2.2129f,1.4732f,-1.6652f,1.5414f,0.6384f,4.2831f,1.6652f,1.5911f,0.5017f,-1.0313f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_9) {transformation: [-1.2411f,-1.4342f,1.3995f,0f,-0.0899f,-1.6047f,-1.7242f,4.2831f,2.0019f,-0.9612f,0.7903f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_10) {transformation: [-0.0337f,0f,-0.0401f,0.0164f,-0.0284f,0.037f,0.0238f,6.0081f,0.0284f,0.037f,-0.0238f,-0.0229f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_11) {transformation: [0.015f,-0.0403f,-0.0299f,-0.0229f,-0.049f,-0.0051f,-0.0177f,6.0081f,0.0107f,0.0331f,-0.0392f,-0.0393f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_12) {transformation: [0.0508f,0.004f,0.012f,0.0164f,-0.0076f,-0.0301f,0.0422f,6.0081f,0.0101f,-0.0427f,-0.0286f,0.0033f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_13) {transformation: [-0.0023f,0.0179f,-0.0492f,-0.0229f,-0.037f,0.0343f,0.0142f,6.0081f,0.037f,0.0354f,0.0111f,0.0033f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_14) {transformation: [-0.0276f,-0.0319f,0.0311f,0f,-0.002f,-0.0357f,-0.0383f,6.0081f,0.0445f,-0.0214f,0.0176f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_15) {transformation: [0f,0f,0f,0f,0f,0f,0f,6.0464f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_16) {transformation: [0f,0f,0f,0f,0f,0f,0f,6.0464f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_17) {transformation: [0f,0f,0f,0f,0f,0f,0f,6.0464f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_18) {transformation: [0f,0f,0f,0f,0f,0f,0f,6.0464f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_19) {transformation: [0f,0f,0f,0f,0f,0f,0f,6.0464f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}