# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_shockwave) {transformation: [1355.5645f,0f,3382.5545f,0f,0f,3644.0678f,0f,84.6376f,-3382.5545f,0f,1355.5645f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_2) {transformation: [-1.3085f,0f,-1.5594f,-0.8906f,-1.1027f,1.4395f,0.9253f,4.1922f,1.1027f,1.4395f,-0.9253f,-1.5268f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_6) {transformation: [0.5815f,-1.5666f,-1.1627f,0.8906f,-1.906f,-0.1975f,-0.6872f,4.1922f,0.4161f,1.2849f,-1.5232f,0.8906f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_7) {transformation: [1.9757f,0.1554f,0.4654f,-1.2723f,-0.2946f,-1.1684f,1.6408f,4.1922f,0.3924f,-1.6598f,-1.1115f,1.0179f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_8) {transformation: [-0.0888f,0.6956f,-1.9111f,1.2723f,-1.4381f,1.3312f,0.5513f,4.1922f,1.4381f,1.3741f,0.4333f,-0.8906f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_9) {transformation: [-1.0719f,-1.2386f,1.2087f,0f,-0.0776f,-1.3859f,-1.4891f,4.1922f,1.7289f,-0.8302f,0.6825f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_10) {transformation: [0f,0f,0f,0f,0f,0f,0f,5.6818f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_11) {transformation: [0f,0f,0f,0f,0f,0f,0f,5.6818f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_12) {transformation: [0f,0f,0f,0f,0f,0f,0f,5.6818f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_13) {transformation: [0f,0f,0f,0f,0f,0f,0f,5.6818f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_14) {transformation: [0f,0f,0f,0f,0f,0f,0f,5.6818f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_15) {transformation: [0f,0f,0f,0f,0f,0f,0f,5.6818f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_16) {transformation: [0f,0f,0f,0f,0f,0f,0f,5.6818f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_17) {transformation: [0f,0f,0f,0f,0f,0f,0f,5.6818f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_18) {transformation: [0f,0f,0f,0f,0f,0f,0f,5.6818f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_19) {transformation: [0f,0f,0f,0f,0f,0f,0f,5.6818f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}