# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_shockwave) {transformation: [1956.0969f,0f,3114.662f,0f,0f,3677.9661f,0f,85.7873f,-3114.662f,0f,1956.0969f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_2) {transformation: [-1.1708f,0f,-1.3953f,-0.7969f,-0.9866f,1.2879f,0.8279f,4.1316f,0.9866f,1.2879f,-0.8279f,-1.3661f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_6) {transformation: [0.5203f,-1.4017f,-1.0403f,0.7969f,-1.7054f,-0.1767f,-0.6149f,4.1316f,0.3723f,1.1496f,-1.3628f,0.7969f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_7) {transformation: [1.7677f,0.1391f,0.4164f,-1.1384f,-0.2635f,-1.0454f,1.4681f,4.1316f,0.3511f,-1.4851f,-0.9945f,0.9107f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_8) {transformation: [-0.0794f,0.6224f,-1.71f,1.1384f,-1.2867f,1.1911f,0.4933f,4.1316f,1.2867f,1.2295f,0.3877f,-0.7969f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_9) {transformation: [-0.9591f,-1.1083f,1.0815f,0f,-0.0695f,-1.24f,-1.3323f,4.1316f,1.5469f,-0.7428f,0.6107f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_10) {transformation: [0f,0f,0f,0f,0f,0f,0f,5.4777f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_11) {transformation: [0f,0f,0f,0f,0f,0f,0f,5.4777f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_12) {transformation: [0f,0f,0f,0f,0f,0f,0f,5.4777f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_13) {transformation: [0f,0f,0f,0f,0f,0f,0f,5.4777f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_14) {transformation: [0f,0f,0f,0f,0f,0f,0f,5.4777f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_15) {transformation: [0f,0f,0f,0f,0f,0f,0f,5.4778f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_16) {transformation: [0f,0f,0f,0f,0f,0f,0f,5.4778f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_17) {transformation: [0f,0f,0f,0f,0f,0f,0f,5.4778f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_18) {transformation: [0f,0f,0f,0f,0f,0f,0f,5.4778f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_19) {transformation: [0f,0f,0f,0f,0f,0f,0f,5.4778f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}