# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_shockwave) {transformation: [-2983.1335f,0f,2208.8123f,0f,0f,3711.8644f,0f,86.8968f,-2208.8123f,0f,-2983.1335f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_2) {transformation: [-1.0331f,0f,-1.2311f,-0.7031f,-0.8705f,1.1364f,0.7305f,4.071f,0.8705f,1.1364f,-0.7305f,-1.2054f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_6) {transformation: [0.4591f,-1.2368f,-0.9179f,0.7031f,-1.5047f,-0.1559f,-0.5425f,4.071f,0.3285f,1.0144f,-1.2025f,0.7031f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_7) {transformation: [1.5598f,0.1227f,0.3674f,-1.0045f,-0.2325f,-0.9224f,1.2954f,4.071f,0.3098f,-1.3103f,-0.8775f,0.8036f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_8) {transformation: [-0.0701f,0.5492f,-1.5088f,1.0045f,-1.1353f,1.0509f,0.4353f,4.071f,1.1353f,1.0848f,0.3421f,-0.7031f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_9) {transformation: [-0.8462f,-0.9779f,0.9542f,0f,-0.0613f,-1.0941f,-1.1756f,4.071f,1.3649f,-0.6554f,0.5388f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_10) {transformation: [0f,0f,0f,0f,0f,0f,0f,5.2706f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_11) {transformation: [0f,0f,0f,0f,0f,0f,0f,5.2706f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_12) {transformation: [0f,0f,0f,0f,0f,0f,0f,5.2706f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_13) {transformation: [0f,0f,0f,0f,0f,0f,0f,5.2706f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_14) {transformation: [0f,0f,0f,0f,0f,0f,0f,5.2706f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_15) {transformation: [0f,0f,0f,0f,0f,0f,0f,5.2706f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_16) {transformation: [0f,0f,0f,0f,0f,0f,0f,5.2706f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_17) {transformation: [0f,0f,0f,0f,0f,0f,0f,5.2706f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_18) {transformation: [0f,0f,0f,0f,0f,0f,0f,5.2706f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_19) {transformation: [0f,0f,0f,0f,0f,0f,0f,5.2706f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}