# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_shockwave) {transformation: [-2293.1431f,0f,-2983.2022f,0f,0f,3762.7119f,0f,88.4813f,2983.2022f,0f,-2293.1431f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_2) {transformation: [-0.8264f,0f,-0.9849f,-0.5625f,-0.6964f,0.9091f,0.5844f,3.98f,0.6964f,0.9091f,-0.5844f,-0.9643f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_6) {transformation: [0.3673f,-0.9894f,-0.7343f,0.5625f,-1.2038f,-0.1247f,-0.434f,3.98f,0.2628f,0.8115f,-0.962f,0.5625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_7) {transformation: [1.2478f,0.0982f,0.2939f,-0.8036f,-0.186f,-0.7379f,1.0363f,3.98f,0.2478f,-1.0483f,-0.702f,0.6429f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_8) {transformation: [-0.0561f,0.4393f,-1.207f,0.8036f,-0.9083f,0.8407f,0.3482f,3.98f,0.9083f,0.8679f,0.2737f,-0.5625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_9) {transformation: [-0.677f,-0.7823f,0.7634f,0f,-0.049f,-0.8753f,-0.9405f,3.98f,1.0919f,-0.5243f,0.4311f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_10) {transformation: [0f,0f,0f,0f,0f,0f,0f,4.9539f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_11) {transformation: [0f,0f,0f,0f,0f,0f,0f,4.9539f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_12) {transformation: [0f,0f,0f,0f,0f,0f,0f,4.9539f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_13) {transformation: [0f,0f,0f,0f,0f,0f,0f,4.9539f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_14) {transformation: [0f,0f,0f,0f,0f,0f,0f,4.9539f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_15) {transformation: [0f,0f,0f,0f,0f,0f,0f,4.9539f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_16) {transformation: [0f,0f,0f,0f,0f,0f,0f,4.9539f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_17) {transformation: [0f,0f,0f,0f,0f,0f,0f,4.9539f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_18) {transformation: [0f,0f,0f,0f,0f,0f,0f,4.9539f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_19) {transformation: [0f,0f,0f,0f,0f,0f,0f,4.9539f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}