# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_shockwave) {transformation: [3806.4804f,0f,-916.4731f,0f,0f,3915.2542f,0f,92.5995f,916.4731f,0f,3806.4804f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_2) {transformation: [-0.2066f,0f,-0.2462f,-0.1406f,-0.1741f,0.2273f,0.1461f,3.6607f,0.1741f,0.2273f,-0.1461f,-0.2411f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_6) {transformation: [0.0918f,-0.2474f,-0.1836f,0.1406f,-0.3009f,-0.0312f,-0.1085f,3.6607f,0.0657f,0.2029f,-0.2405f,0.1406f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_7) {transformation: [0.312f,0.0245f,0.0735f,-0.2009f,-0.0465f,-0.1845f,0.2591f,3.6607f,0.062f,-0.2621f,-0.1755f,0.1607f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_8) {transformation: [-0.014f,0.1098f,-0.3018f,0.2009f,-0.2271f,0.2102f,0.0871f,3.6607f,0.2271f,0.217f,0.0684f,-0.1406f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_9) {transformation: [-0.1692f,-0.1956f,0.1908f,0f,-0.0123f,-0.2188f,-0.2351f,3.6607f,0.273f,-0.1311f,0.1078f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_10) {transformation: [0f,0f,0f,0f,0f,0f,0f,3.9148f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_11) {transformation: [0f,0f,0f,0f,0f,0f,0f,3.9148f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_12) {transformation: [0f,0f,0f,0f,0f,0f,0f,3.9148f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_13) {transformation: [0f,0f,0f,0f,0f,0f,0f,3.9148f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_14) {transformation: [0f,0f,0f,0f,0f,0f,0f,3.9148f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_15) {transformation: [0f,0f,0f,0f,0f,0f,0f,3.9148f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_16) {transformation: [0f,0f,0f,0f,0f,0f,0f,3.9148f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_17) {transformation: [0f,0f,0f,0f,0f,0f,0f,3.9148f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_18) {transformation: [0f,0f,0f,0f,0f,0f,0f,3.9148f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_19) {transformation: [0f,0f,0f,0f,0f,0f,0f,3.9148f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}