# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:ginunga/animations/animation.model.idle/zzz/apply_frame {frame: 45}
scoreboard players add @s aj.animation.model.idle.frame 1