# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tp @s ~ ~ ~ ~ ~
data merge entity @s {Invulnerable:1b}
execute if entity @n[tag=aj.ginunga.root,tag=ch_tm.boss.ginunga.action.warp] as @n[tag=aj.ginunga.locator.mouse] at @s run playsound trip_magic:entity.ginunga.tp.in hostile @a ~ ~ ~ 1 1
particle dust{color:[0.02,0,0.314],scale:1} ~ ~0.5 ~ 0.25 0.5 0.25 0.01 50 force
particle dust{color:[0.239,0,0.431],scale:1} ~ ~0.5 ~ 0.25 0.5 0.25 0.01 50 force
execute if entity @n[tag=aj.ginunga.root] at @n[tag=ch_tm.player.target.ginunga] run particle dust{color:[0.239,0,0.431],scale:1} ~ ~0.5 ~ 0.25 0.5 0.25 0.01 50 force