# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute as @n[tag=aj.ginunga.root,tag=ch_tm.boss.ginunga.action.warp] at @s run function ch_trip_and_magic_boss:ginga/animation/warp/tp
