# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.ginunga.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'ginunga', 'function_path': 'animated_java:ginunga/animations/pause_all'}
tag @s remove aj.ginunga.animation.animation.model.idle.playing
tag @s remove aj.ginunga.animation.animation.model.cry.playing
tag @s remove aj.ginunga.animation.animation.model.move_start.playing
tag @s remove aj.ginunga.animation.animation.model.move.playing
tag @s remove aj.ginunga.animation.animation.model.warp_in.playing
tag @s remove aj.ginunga.animation.animation.model.warp_out.playing
tag @s remove aj.ginunga.animation.animation.model.shot_bullet.playing
tag @s remove aj.ginunga.animation.animation.model.death.playing
tag @s remove aj.ginunga.animation.animation.model.set_rand_mine.playing
tag @s remove aj.ginunga.animation.animation.model.attack.playing
tag @s remove aj.ginunga.animation.animation.model.move_attack.playing
tag @s remove aj.ginunga.animation.animation.model.afraid_back.playing
tag @s remove aj.ginunga.animation.animation.model.vertigo.start.playing
tag @s remove aj.ginunga.animation.animation.model.vertigo.loop.playing
tag @s remove aj.ginunga.animation.animation.model.vertigo.end.playing
tag @s remove aj.ginunga.animation.animation.model.chain_blast.cry.playing
tag @s remove aj.ginunga.animation.animation.model.chain_blast.playing
tag @s remove aj.ginunga.animation.animation.model.angel_wisper.cry.playing
tag @s remove aj.ginunga.animation.animation.model.angel_wisper.playing
tag @s remove aj.ginunga.animation.animation.model.afraid_front.playing