# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.new
function animated_java:global/internal/gu/convert_uuid_array_to_string
tp @s ^0 ^1.2 ^0 ~0 ~0
data merge entity @s {Silent:1b,NoGravity:1b,DeathLootTable:"ch_trip_and_magic_boss:unset",Size:0,PersistenceRequired:1b,NoAI:1b,active_effects:[{id:"minecraft:invisibility",amplifier:10,duration:1000000,show_particles:0b,show_icon:0b,ambient:0b}],Health:1000f,attributes:[{id:"minecraft:attack_damage",base:0},{id:"minecraft:knockback_resistance",base:9999},{id:"minecraft:max_health",base:1000},{id:"minecraft:movement_speed",base:0},{id:"minecraft:step_height",base:0},{id:"minecraft:scale",base:2}],DeathTime:19,OnGround:0b,Tags:["ch_trip_and_magic_bosses_intaract","ch_trip_and_magic_bosses_ginga_head_hitbox","ch_trip_and_magic_bosses_intaract_ginga","ch_trip_and_magic_bosses_intaract_weak_parts"]}
