# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:temp args merge from entity @s data.locators.mouse
function animated_java:ginunga/zzz/at_all_locators/execute_at_transform with storage aj:temp args
data modify storage aj:temp args merge from entity @s data.locators.left_arm
function animated_java:ginunga/zzz/at_all_locators/execute_at_transform with storage aj:temp args
data modify storage aj:temp args merge from entity @s data.locators.right_arm
function animated_java:ginunga/zzz/at_all_locators/execute_at_transform with storage aj:temp args
data modify storage aj:temp args merge from entity @s data.locators.intaract2
function animated_java:ginunga/zzz/at_all_locators/execute_at_transform with storage aj:temp args
data modify storage aj:temp args merge from entity @s data.locators.intaract
function animated_java:ginunga/zzz/at_all_locators/execute_at_transform with storage aj:temp args
data modify storage aj:temp args merge from entity @s data.locators.shadow
function animated_java:ginunga/zzz/at_all_locators/execute_at_transform with storage aj:temp args