# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.animation.model.stay.frame dummy
scoreboard objectives add aj.animation.model.prep_start.frame dummy
scoreboard objectives add aj.animation.model.prep.frame dummy