# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:ginunga/animations/animation.model.move/zzz/apply_frame {frame: 35}
scoreboard players add @s aj.animation.model.move.frame 1