# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute positioned ~-2.5 ~ ~-2.5 as @e[tag=!ls_tm_magic_pl_freeze,dx=5,dy=4,dz=5,type=#ls_trip_and_magic:mobs_and_player_and_collision_entity] at @s positioned ~2.5 ~ ~2.5 run damage @s 5 ls_trip_and_magic:magic/ice_lv2_break by @e[tag=ls_tm_magic_pl_freeze,sort=nearest,limit=1]
execute positioned ~-2.5 ~ ~-2.5 as @e[tag=!ls_tm_magic_pl_freeze,dx=5,dy=4,dz=5,type=#ls_trip_and_magic:mobs_and_player_and_collision_entity] at @s positioned ~2.5 ~ ~2.5 run function ls_trip_and_magic:magic/effect/frost/start {"time":"5"}
particle block{block_state:packed_ice} ~ ~1 ~ 1.25 1.0 1.25 0. 250
playsound trip_magic:magic.ice.hiber_latch.break player @a ~ ~ ~ 2 1
function ls_trip_and_magic:magic/magic_temp/hit