# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_ground) {transformation: [-0.0001f,0f,0f,0f,0f,0.0001f,0f,0f,0f,0f,-0.0001f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
particle block{block_state:packed_ice} ~ ~0.125 ~ 1.25 0.0 1.25 0. 250
playsound block.glass.break player @a ~ ~ ~ 2 0
execute as @n[tag=aj.hiber_latch.root] at @s run function animated_java:hiber_latch/remove/this