# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.hiber_latch.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'hiber_latch', 'function_path': 'animated_java:hiber_latch/animations/animation.model.main/stop'}
tag @s remove aj.hiber_latch.animation.animation.model.main.playing
scoreboard players set @s aj.animation.model.main.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:hiber_latch/animations/animation.model.main/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only