# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:ginunga/animations/animation.model.vertigo.loop/zzz/apply_frame {frame: 76}
scoreboard players add @s aj.animation.model.vertigo.loop.frame 1