# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @n[tag=aj.ginunga.root] remove ch_tm_bosses_ginga_during_animation
tag @n[tag=aj.ginunga.root] remove ch_tm_bosses_ginga_during_animate_cooldown
tag @n[tag=aj.ginunga.root] remove ch_tm.boss.ginunga.action.chain_blast.prep
tag @n[tag=aj.ginunga.root] remove ch_tm.boss.ginunga.action.chain_blast
tag @n[tag=aj.ginunga.root] remove ch_tm.boss.ginunga.bypass.jam
scoreboard players reset @n[tag=aj.ginunga.root] ch_tm_bosses_ginga_chain_blast
function animated_java:chain_blast/remove/all