# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.explode_large_effect.root] run return 0
execute on passengers if entity @s[tag=aj.explode_large_effect.data] unless data entity @s {data:{rigHash: '7c3a35c27ded718994657915d16cd0ac96b923b8442c98f85479b4abe2e04f09'}} on vehicle run function animated_java:explode_large_effect/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1