# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_bone3) {transformation: [-0.2f,0f,0f,-0.375f,0f,0.2f,0f,0.5f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone2) {transformation: [-0.2f,0f,0f,0.3125f,0f,0.2f,0f,0.5625f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone1) {transformation: [-1f,0f,0f,0f,0f,0.2f,0f,0.5625f,0f,0f,-0.2f,-0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone) {transformation: [-1f,0f,0f,0f,0f,0.2f,0f,0.5625f,0f,0f,-0.2f,0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone9) {transformation: [-0.1414f,0f,-0.7071f,-0.3094f,0f,0.2f,0f,0.5f,0.1414f,0f,-0.7071f,0.3094f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone8) {transformation: [-0.1414f,0f,-0.7071f,0.2652f,0f,0.2f,0f,0.5f,0.1414f,0f,-0.7071f,-0.2652f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone7) {transformation: [-0.7071f,0f,-0.1414f,-0.2652f,0f,0.2f,0f,0.5625f,0.7071f,0f,-0.1414f,-0.2652f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone6) {transformation: [-0.7071f,0f,-0.1414f,0.3094f,0f,0.2f,0f,0.5625f,0.7071f,0f,-0.1414f,0.3094f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}