# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.explode_large_effect.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'explode_large_effect', 'function_path': 'animated_java:explode_large_effect/animations/animation.model.explode/next_frame'}
execute if score @s aj.animation.model.explode.frame matches 221.. run scoreboard players set @s aj.animation.model.explode.frame 1
data remove storage aj:temp args
execute store result storage aj:temp args.frame int 1 run scoreboard players get @s aj.animation.model.explode.frame
execute at @s run function animated_java:explode_large_effect/animations/animation.model.explode/zzz/apply_frame with storage aj:temp args
scoreboard players add @s aj.animation.model.explode.frame 1