# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.explode_large_effect.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'explode_large_effect', 'function_path': 'animated_java:explode_large_effect/animations/animation.model.explode/play'}
tag @s add aj.explode_large_effect.animation.animation.model.explode.playing
scoreboard players set @s aj.animation.model.explode.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:explode_large_effect/animations/animation.model.explode/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only