# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:ginunga/remove/zzz/this/kill_locator with entity @s data.locators.locator_mouse
function animated_java:ginunga/remove/zzz/this/kill_locator with entity @s data.locators.locator_left_arm
function animated_java:ginunga/remove/zzz/this/kill_locator with entity @s data.locators.locator_right_arm
function animated_java:ginunga/remove/zzz/this/kill_locator with entity @s data.locators.locator_intaract2
function animated_java:ginunga/remove/zzz/this/kill_locator with entity @s data.locators.locator_intaract
function animated_java:ginunga/remove/zzz/this/kill_locator with entity @s data.locators.locator_shadow