# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.chain_blast.root] run return 0
execute on passengers if entity @s[tag=aj.chain_blast.data] unless data entity @s {data:{rigHash: '1be1b1c25a9e922c4a76a16a9a77725c71a8bf2335015554fcd534cf118feba1'}} on vehicle run function animated_java:chain_blast/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1