# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.chain_blast.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
execute if entity @s[tag=aj.chain_blast.animation.animation.model.summon.playing] run function animated_java:chain_blast/animations/animation.model.summon/zzz/on_tick
execute if entity @s[tag=aj.chain_blast.animation.animation.model.blast.playing] run function animated_java:chain_blast/animations/animation.model.blast/zzz/on_tick
execute at @s on passengers run rotate @s ~ ~