# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_eyes) {transformation: [-1f,0f,0f,-0.0156f,0f,1f,0f,1.7249f,0f,0f,-1f,0.3065f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.3811f,0f,0f,-1f,0.0552f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_fabric_overray) {transformation: [-1f,0f,0f,0f,0f,0.9848f,0.1736f,1.3811f,0f,0.1736f,-0.9848f,0.0552f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_fabric) {transformation: [-1f,0f,0f,0f,0f,0.9848f,0.1736f,1.3811f,0f,0.1736f,-0.9848f,0.0552f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"mouse":{"posx":-3.737800473764221e-17,"posy":1.474855433920498,"posz":0.3052145709576527,"roty":0,"rotx":0}}}
execute on vehicle unless entity @s[tag=aj.transforms_only] at @s run function animated_java:ginunga/animations/animation.model.move_attack/zzz/frames/44_root_commands