# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.magic_crafting_table.root] run return 0
execute on passengers if entity @s[tag=aj.magic_crafting_table.data] unless data entity @s {data:{rigHash: 'a2c9269e0fddcadfb8fcb43c97fcd47a901ad763e672b94e40ef79b83cfb646e'}} on vehicle run function animated_java:magic_crafting_table/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1