# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.magic_crafting_table.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
execute if entity @s[tag=aj.magic_crafting_table.animation.animation.model.stay.playing] run function animated_java:magic_crafting_table/animations/animation.model.stay/zzz/on_tick
execute if entity @s[tag=aj.magic_crafting_table.animation.animation.model.prep_start.playing] run function animated_java:magic_crafting_table/animations/animation.model.prep_start/zzz/on_tick
execute if entity @s[tag=aj.magic_crafting_table.animation.animation.model.prep.playing] run function animated_java:magic_crafting_table/animations/animation.model.prep/zzz/on_tick
execute on passengers if entity @s[tag=aj.magic_crafting_table.data] run function animated_java:magic_crafting_table/root/zzz/on_tick/locators_and_cameras
execute at @s on passengers run rotate @s ~ ~