# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.hiber_latch.root] run return 0
execute on passengers if entity @s[tag=aj.hiber_latch.data] unless data entity @s {data:{rigHash: '39dda79a108f7b57068e0c77992145e5ea281e860592e9136b1e7c1643e110e5'}} on vehicle run function animated_java:hiber_latch/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1