# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:temp args.uuid set from entity @s data.uuids.locator_mouse
function animated_java:ginunga/zzz/as_all_locators/execute_as_uuid with storage aj:temp args
data modify storage aj:temp args.uuid set from entity @s data.uuids.locator_left_arm
function animated_java:ginunga/zzz/as_all_locators/execute_as_uuid with storage aj:temp args
data modify storage aj:temp args.uuid set from entity @s data.uuids.locator_right_arm
function animated_java:ginunga/zzz/as_all_locators/execute_as_uuid with storage aj:temp args
data modify storage aj:temp args.uuid set from entity @s data.uuids.locator_intaract2
function animated_java:ginunga/zzz/as_all_locators/execute_as_uuid with storage aj:temp args
data modify storage aj:temp args.uuid set from entity @s data.uuids.locator_intaract
function animated_java:ginunga/zzz/as_all_locators/execute_as_uuid with storage aj:temp args
data modify storage aj:temp args.uuid set from entity @s data.uuids.locator_shadow
function animated_java:ginunga/zzz/as_all_locators/execute_as_uuid with storage aj:temp args