# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.hiber_latch.node.bone16] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone16 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.hiber_latch.node.bone4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.hiber_latch.node.bone9] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone9 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.hiber_latch.node.bone6] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone6 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.hiber_latch.node.bone13] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone13 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.hiber_latch.node.bone17] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone17 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.hiber_latch.node.bone19] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone19 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.hiber_latch.node.bone7] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone7 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.hiber_latch.node.bone] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.hiber_latch.node.bone12] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone12 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.hiber_latch.node.bone15] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone15 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.hiber_latch.node.bone8] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone8 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.hiber_latch.node.bone1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.hiber_latch.node.bone20] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone20 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.hiber_latch.node.bone11] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone11 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.hiber_latch.node.bone14] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone14 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.hiber_latch.node.bone2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.hiber_latch.node.bone10] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone10 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.hiber_latch.node.bone18] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone18 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.hiber_latch.node.bone5] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.hiber_latch.node.bone3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.hiber_latch.node.ground] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_ground set from storage aj:uuid main.out