# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.magic_crafting_table.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'magic_crafting_table', 'function_path': 'animated_java:magic_crafting_table/animations/animation.model.stay/stop'}
tag @s remove aj.magic_crafting_table.animation.animation.model.stay.playing
scoreboard players set @s aj.animation.model.stay.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:magic_crafting_table/animations/animation.model.stay/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only