# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_eyes) {transformation: [0f,0f,0f,-0.0156f,0f,0f,0f,1.4296f,0f,0f,0f,0.3805f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.7071f,0.7071f,1.3642f,0f,0.7071f,-0.7071f,-0.0403f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_fabric_overray) {transformation: [-1f,0f,0f,0f,0f,0.9537f,0.3007f,1.3642f,0f,0.3007f,-0.9537f,-0.0403f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_fabric) {transformation: [-1f,0f,0f,0f,0f,0.9537f,0.3007f,1.3642f,0f,0.3007f,-0.9537f,-0.0403f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"mouse":{"posx":-2.4837455718088415e-17,"posy":1.2536831976051643,"posz":0.2028132171282464,"roty":0,"rotx":45.00000000000001}}}

execute as @n[tag=aj.ginunga.root,scores={ch_tm_bosses_vertigo_tick=4..}] at @s run function ch_trip_and_magic_boss:ginga/prosses/vertigo/end