# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.ginunga.root] run return 0
execute on passengers if entity @s[tag=aj.ginunga.data] unless data entity @s {data:{rigHash: '668739199fe7f9660686ccaf8aaf2a4c033153ad3e64a8b2a1345d424a244966'}} on vehicle run function animated_java:ginunga/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1