# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.ginunga.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
execute if entity @s[tag=aj.ginunga.animation.animation.model.idle.playing] run function animated_java:ginunga/animations/animation.model.idle/zzz/on_tick
execute if entity @s[tag=aj.ginunga.animation.animation.model.cry.playing] run function animated_java:ginunga/animations/animation.model.cry/zzz/on_tick
execute if entity @s[tag=aj.ginunga.animation.animation.model.move_start.playing] run function animated_java:ginunga/animations/animation.model.move_start/zzz/on_tick
execute if entity @s[tag=aj.ginunga.animation.animation.model.move.playing] run function animated_java:ginunga/animations/animation.model.move/zzz/on_tick
execute if entity @s[tag=aj.ginunga.animation.animation.model.warp_in.playing] run function animated_java:ginunga/animations/animation.model.warp_in/zzz/on_tick
execute if entity @s[tag=aj.ginunga.animation.animation.model.warp_out.playing] run function animated_java:ginunga/animations/animation.model.warp_out/zzz/on_tick
execute if entity @s[tag=aj.ginunga.animation.animation.model.shot_bullet.playing] run function animated_java:ginunga/animations/animation.model.shot_bullet/zzz/on_tick
execute if entity @s[tag=aj.ginunga.animation.animation.model.death.playing] run function animated_java:ginunga/animations/animation.model.death/zzz/on_tick
execute if entity @s[tag=aj.ginunga.animation.animation.model.set_rand_mine.playing] run function animated_java:ginunga/animations/animation.model.set_rand_mine/zzz/on_tick
execute if entity @s[tag=aj.ginunga.animation.animation.model.attack.playing] run function animated_java:ginunga/animations/animation.model.attack/zzz/on_tick
execute if entity @s[tag=aj.ginunga.animation.animation.model.move_attack.playing] run function animated_java:ginunga/animations/animation.model.move_attack/zzz/on_tick
execute if entity @s[tag=aj.ginunga.animation.animation.model.afraid_back.playing] run function animated_java:ginunga/animations/animation.model.afraid_back/zzz/on_tick
execute if entity @s[tag=aj.ginunga.animation.animation.model.vertigo.start.playing] run function animated_java:ginunga/animations/animation.model.vertigo.start/zzz/on_tick
execute if entity @s[tag=aj.ginunga.animation.animation.model.vertigo.loop.playing] run function animated_java:ginunga/animations/animation.model.vertigo.loop/zzz/on_tick
execute if entity @s[tag=aj.ginunga.animation.animation.model.vertigo.end.playing] run function animated_java:ginunga/animations/animation.model.vertigo.end/zzz/on_tick
execute if entity @s[tag=aj.ginunga.animation.animation.model.chain_blast.cry.playing] run function animated_java:ginunga/animations/animation.model.chain_blast.cry/zzz/on_tick
execute if entity @s[tag=aj.ginunga.animation.animation.model.chain_blast.playing] run function animated_java:ginunga/animations/animation.model.chain_blast/zzz/on_tick
execute if entity @s[tag=aj.ginunga.animation.animation.model.angel_wisper.cry.playing] run function animated_java:ginunga/animations/animation.model.angel_wisper.cry/zzz/on_tick
execute if entity @s[tag=aj.ginunga.animation.animation.model.angel_wisper.playing] run function animated_java:ginunga/animations/animation.model.angel_wisper/zzz/on_tick
execute if entity @s[tag=aj.ginunga.animation.animation.model.afraid_front.playing] run function animated_java:ginunga/animations/animation.model.afraid_front/zzz/on_tick
execute on passengers if entity @s[tag=aj.ginunga.data] run function animated_java:ginunga/root/zzz/on_tick/locators_and_cameras
execute at @s on passengers run rotate @s ~ ~