# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.explode_large_effect.node.1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.explode_large_effect.node.3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.explode_large_effect.node.4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.explode_large_effect.node.5] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.explode_large_effect.node.shockwave] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_shockwave set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.explode_large_effect.node.2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.explode_large_effect.node.6] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_6 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.explode_large_effect.node.7] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_7 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.explode_large_effect.node.8] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_8 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.explode_large_effect.node.9] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_9 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.explode_large_effect.node.10] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_10 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.explode_large_effect.node.11] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_11 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.explode_large_effect.node.12] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_12 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.explode_large_effect.node.13] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_13 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.explode_large_effect.node.14] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_14 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.explode_large_effect.node.15] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_15 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.explode_large_effect.node.16] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_16 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.explode_large_effect.node.17] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_17 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.explode_large_effect.node.18] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_18 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.explode_large_effect.node.19] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_19 set from storage aj:uuid main.out