# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.chain_blast.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'chain_blast', 'function_path': 'animated_java:chain_blast/set_default_pose'}
execute on passengers if entity @s[tag=aj.chain_blast.bone.blast1] run data merge entity @s {transformation: [0f,0f,-1f,0.0313f,0f,1f,0f,0.5f,1f,0f,0f,0f,0f,0f,0f,1f], start_interpolation: -1}
execute on passengers if entity @s[tag=aj.chain_blast.bone.blast] run data merge entity @s {transformation: [-1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1}
execute on passengers if entity @s[tag=aj.chain_blast.bone.bone5] run data merge entity @s {transformation: [-1f,0f,0f,0f,0f,1f,0f,3f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1}
execute on passengers if entity @s[tag=aj.chain_blast.bone.bone4] run data merge entity @s {transformation: [-1f,0f,0f,0f,0f,1f,0f,2.25f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1}
execute on passengers if entity @s[tag=aj.chain_blast.bone.bone3] run data merge entity @s {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1}
execute on passengers if entity @s[tag=aj.chain_blast.bone.bone2] run data merge entity @s {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.75f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1}
execute on passengers if entity @s[tag=aj.chain_blast.bone.bone1] run data merge entity @s {transformation: [-1f,0f,0f,0.0313f,0f,1f,0f,0f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1}
execute on passengers if entity @s[tag=aj.chain_blast.bone.bone10] run data merge entity @s {transformation: [0f,0f,-1f,0f,0f,1f,0f,3f,1f,0f,0f,0f,0f,0f,0f,1f], start_interpolation: -1}
execute on passengers if entity @s[tag=aj.chain_blast.bone.bone9] run data merge entity @s {transformation: [0f,0f,-1f,0f,0f,1f,0f,2.25f,1f,0f,0f,0f,0f,0f,0f,1f], start_interpolation: -1}
execute on passengers if entity @s[tag=aj.chain_blast.bone.bone8] run data merge entity @s {transformation: [0f,0f,-1f,0f,0f,1f,0f,1.5f,1f,0f,0f,0f,0f,0f,0f,1f], start_interpolation: -1}
execute on passengers if entity @s[tag=aj.chain_blast.bone.bone7] run data merge entity @s {transformation: [0f,0f,-1f,0f,0f,1f,0f,0.75f,1f,0f,0f,0f,0f,0f,0f,1f], start_interpolation: -1}
execute on passengers if entity @s[tag=aj.chain_blast.bone.bone6] run data merge entity @s {transformation: [0f,0f,-1f,0f,0f,1f,0f,0f,1f,0f,0f,-0.0312f,0f,0f,0f,1f], start_interpolation: -1}
execute on passengers if entity @s[tag=aj.chain_blast.bone.bone20] run data merge entity @s {transformation: [1f,0f,0f,0f,0f,1f,0f,3f,0f,0f,1f,0f,0f,0f,0f,1f], start_interpolation: -1}
execute on passengers if entity @s[tag=aj.chain_blast.bone.bone19] run data merge entity @s {transformation: [1f,0f,0f,0f,0f,1f,0f,2.25f,0f,0f,1f,0f,0f,0f,0f,1f], start_interpolation: -1}
execute on passengers if entity @s[tag=aj.chain_blast.bone.bone18] run data merge entity @s {transformation: [1f,0f,0f,0f,0f,1f,0f,1.5f,0f,0f,1f,0f,0f,0f,0f,1f], start_interpolation: -1}
execute on passengers if entity @s[tag=aj.chain_blast.bone.bone17] run data merge entity @s {transformation: [1f,0f,0f,0f,0f,1f,0f,0.75f,0f,0f,1f,0f,0f,0f,0f,1f], start_interpolation: -1}
execute on passengers if entity @s[tag=aj.chain_blast.bone.bone16] run data merge entity @s {transformation: [1f,0f,0f,-0.0312f,0f,1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,1f], start_interpolation: -1}
execute on passengers if entity @s[tag=aj.chain_blast.bone.bone15] run data merge entity @s {transformation: [0f,0f,1f,0f,0f,1f,0f,3f,-1f,0f,0f,0f,0f,0f,0f,1f], start_interpolation: -1}
execute on passengers if entity @s[tag=aj.chain_blast.bone.bone14] run data merge entity @s {transformation: [0f,0f,1f,0f,0f,1f,0f,2.25f,-1f,0f,0f,0f,0f,0f,0f,1f], start_interpolation: -1}
execute on passengers if entity @s[tag=aj.chain_blast.bone.bone13] run data merge entity @s {transformation: [0f,0f,1f,0f,0f,1f,0f,1.5f,-1f,0f,0f,0f,0f,0f,0f,1f], start_interpolation: -1}
execute on passengers if entity @s[tag=aj.chain_blast.bone.bone12] run data merge entity @s {transformation: [0f,0f,1f,0f,0f,1f,0f,0.75f,-1f,0f,0f,0f,0f,0f,0f,1f], start_interpolation: -1}
execute on passengers if entity @s[tag=aj.chain_blast.bone.bone11] run data merge entity @s {transformation: [0f,0f,1f,0f,0f,1f,0f,0f,-1f,0f,0f,0.0313f,0f,0f,0f,1f], start_interpolation: -1}
execute on passengers if entity @s[tag=aj.chain_blast.bone.bone] run data merge entity @s {transformation: [-1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1}