# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players set @n[tag=aj.ginunga.root] ch_tm_bosses_action 102
kill @e[tag=ch_tm.boss.marker.ginunga.set_axis]