# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:ginunga/root/zzz/on_tick/select_locator_mouse with entity @s data.locators.mouse
function animated_java:ginunga/root/zzz/on_tick/select_locator_left_arm with entity @s data.locators.left_arm
function animated_java:ginunga/root/zzz/on_tick/select_locator_right_arm with entity @s data.locators.right_arm
function animated_java:ginunga/root/zzz/on_tick/select_locator_intaract2 with entity @s data.locators.intaract2
function animated_java:ginunga/root/zzz/on_tick/select_locator_intaract with entity @s data.locators.intaract
function animated_java:ginunga/root/zzz/on_tick/select_locator_shadow with entity @s data.locators.shadow