# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @n[tag=aj.ginunga.root] remove ch_tm.boss.ginunga.action.move.prep
tag @n[tag=aj.ginunga.root] add ch_tm.boss.ginunga.action.move