# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives remove aj.animation.model.idle.frame
scoreboard objectives remove aj.animation.model.cry.frame
scoreboard objectives remove aj.animation.model.move_start.frame
scoreboard objectives remove aj.animation.model.move.frame
scoreboard objectives remove aj.animation.model.warp_in.frame
scoreboard objectives remove aj.animation.model.warp_out.frame
scoreboard objectives remove aj.animation.model.shot_bullet.frame
scoreboard objectives remove aj.animation.model.death.frame
scoreboard objectives remove aj.animation.model.set_rand_mine.frame
scoreboard objectives remove aj.animation.model.attack.frame
scoreboard objectives remove aj.animation.model.move_attack.frame
scoreboard objectives remove aj.animation.model.afraid_back.frame
scoreboard objectives remove aj.animation.model.vertigo.start.frame
scoreboard objectives remove aj.animation.model.vertigo.loop.frame
scoreboard objectives remove aj.animation.model.vertigo.end.frame
scoreboard objectives remove aj.animation.model.chain_blast.cry.frame
scoreboard objectives remove aj.animation.model.chain_blast.frame
scoreboard objectives remove aj.animation.model.angel_wisper.cry.frame
scoreboard objectives remove aj.animation.model.angel_wisper.frame
scoreboard objectives remove aj.animation.model.afraid_front.frame
tellraw @a [[{"text":"\n[","color":"gray"},{"text":"AJ","color":"aqua"},"] ",[{"text":"(from ","color":"gray","italic":true},"ginunga",")"]," -> "],{"text":"Successfully removed known animation scoreboard objectives.","color":"red"},{"text":"\nIf you have exported multiple times you may have to manually remove some objectives from previous exports manually, as Animated Java can only remove the latest export's objectives.","color":"gray","italic":true},["\n"]]